// Code generated by archesai. DO NOT EDIT.

package controllers

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"

	"github.com/archesai/archesai/internal/adapters/http/server"
	commands "github.com/archesai/archesai/internal/application/commands/label"
	queries "github.com/archesai/archesai/internal/application/queries/label"
	"github.com/archesai/archesai/internal/core/entities"
)

// LabelController handles HTTP requests for label endpoints.
type LabelController struct {
	createLabelHandler *commands.CreateLabelCommandHandler
	updateLabelHandler *commands.UpdateLabelCommandHandler
	deleteLabelHandler *commands.DeleteLabelCommandHandler
	getLabelHandler    *queries.GetLabelQueryHandler
	listLabelsHandler  *queries.ListLabelsQueryHandler
}

// NewLabelController creates a new label controller with injected handlers.
func NewLabelController(
	createLabelHandler *commands.CreateLabelCommandHandler,
	updateLabelHandler *commands.UpdateLabelCommandHandler,
	deleteLabelHandler *commands.DeleteLabelCommandHandler,
	getLabelHandler *queries.GetLabelQueryHandler,
	listLabelsHandler *queries.ListLabelsQueryHandler,
) *LabelController {
	return &LabelController{
		createLabelHandler: createLabelHandler,
		updateLabelHandler: updateLabelHandler,
		deleteLabelHandler: deleteLabelHandler,
		getLabelHandler:    getLabelHandler,
		listLabelsHandler:  listLabelsHandler,
	}
}

// RegisterLabelRoutes registers all HTTP routes for the label domain.
func RegisterLabelRoutes(router server.EchoRouter, controller *LabelController) {
	router.POST("/labels", controller.CreateLabel)
	router.GET("/labels/:id", controller.GetLabel)
	router.GET("/labels", controller.ListLabels)
	router.PATCH("/labels/:id", controller.UpdateLabel)
	router.DELETE("/labels/:id", controller.DeleteLabel)
}

// ============================================================================
// CreateLabel - POST /labels
// ============================================================================

// Request types
// CreateLabelRequestBody defines the request body for CreateLabel
type CreateLabelRequestBody struct {
	Name string `json:"name"`
}

type CreateLabelRequest struct {
	Body *CreateLabelRequestBody
}

// Response types

type CreateLabelResponse interface {
	VisitCreateLabelResponse(w http.ResponseWriter) error
}

type CreateLabel201Response struct {
	Data entities.Label `json:"data"`
}

func (response CreateLabel201Response) VisitCreateLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateLabel400Response struct {
	server.BadRequestResponse
}

func (response CreateLabel400Response) VisitCreateLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.BadRequestResponse)
}

type CreateLabel401Response struct {
	server.UnauthorizedResponse
}

func (response CreateLabel401Response) VisitCreateLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.UnauthorizedResponse)
}

// Handler method

// CreateLabel handles the POST /labels endpoint.
func (c *LabelController) CreateLabel(ctx echo.Context) error {
	reqCtx := ctx.Request().Context()
	request := CreateLabelRequest{}

	// Extract session ID from context for authenticated operations
	var sessionID uuid.UUID
	if sid := ctx.Get("sessionID"); sid != nil {
		sessionID = sid.(uuid.UUID)
	} else {
		return echo.NewHTTPError(http.StatusUnauthorized, "session required")
	}

	// Request body
	request.Body = &CreateLabelRequestBody{}
	if err := ctx.Bind(request.Body); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}

	// Set auth scopes
	ctx.Set(server.BearerAuthScopes, []string{})

	// Determine which handler to call based on operation
	// Command handler

	// Map request to command parameters
	cmd := commands.NewCreateLabelCommand(
		sessionID,         // SessionID for authenticated operations
		request.Body.Name, // Name
	)
	result, err := c.createLabelHandler.Handle(reqCtx, cmd)
	if err != nil {
		return err
	}
	return ctx.JSON(http.StatusCreated, map[string]interface{}{
		"data": result,
	})
}

// ============================================================================
// GetLabel - GET /labels/{id}
// ============================================================================

// Request types

type GetLabelRequest struct {
	ID uuid.UUID `json:"id"`
}

// Response types

type GetLabelResponse interface {
	VisitGetLabelResponse(w http.ResponseWriter) error
}

type GetLabel200Response struct {
	Data entities.Label `json:"data"`
}

func (response GetLabel200Response) VisitGetLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetLabel404Response struct {
	server.NotFoundResponse
}

func (response GetLabel404Response) VisitGetLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.NotFoundResponse)
}

// Handler method

// GetLabel handles the GET /labels/{id} endpoint.
func (c *LabelController) GetLabel(ctx echo.Context) error {
	reqCtx := ctx.Request().Context()
	request := GetLabelRequest{}

	// Extract session ID from context for authenticated operations
	var sessionID uuid.UUID
	if sid := ctx.Get("sessionID"); sid != nil {
		sessionID = sid.(uuid.UUID)
	} else {
		return echo.NewHTTPError(http.StatusUnauthorized, "session required")
	}

	// Path parameter "id"
	var id uuid.UUID
	if err := runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true}); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}
	request.ID = id

	// Set auth scopes
	ctx.Set(server.BearerAuthScopes, []string{})

	// Determine which handler to call based on operation
	// Query handler
	query := queries.NewGetLabelQuery(
		sessionID,  // SessionID for authenticated operations
		request.ID, // ID
	)

	result, err := c.getLabelHandler.Handle(reqCtx, query)
	if err != nil {
		return err
	}

	return ctx.JSON(http.StatusOK, map[string]interface{}{
		"data": result,
	})
}

// ============================================================================
// ListLabels - GET /labels
// ============================================================================

// Request types
// ListLabelsParams defines parameters for ListLabels
type ListLabelsParams struct {
	Filter map[string]any   `json:"filter,omitempty"`
	Page   map[string]any   `json:"page,omitempty"`
	Sort   []map[string]any `json:"sort,omitempty"`
}

type ListLabelsRequest struct {
	Params ListLabelsParams
}

// Response types

type ListLabelsResponse interface {
	VisitListLabelsResponse(w http.ResponseWriter) error
}

// ListLabels200ResponseMeta defines the meta structure
type ListLabels200ResponseMeta struct {
	Total float64 `json:"total"`
}

type ListLabels200Response struct {
	Data []entities.Label          `json:"data"`
	Meta ListLabels200ResponseMeta `json:"meta"`
}

func (response ListLabels200Response) VisitListLabelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListLabels400Response struct {
	server.BadRequestResponse
}

func (response ListLabels400Response) VisitListLabelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.BadRequestResponse)
}

type ListLabels401Response struct {
	server.UnauthorizedResponse
}

func (response ListLabels401Response) VisitListLabelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.UnauthorizedResponse)
}

// Handler method

// ListLabels handles the GET /labels endpoint.
func (c *LabelController) ListLabels(ctx echo.Context) error {
	reqCtx := ctx.Request().Context()
	request := ListLabelsRequest{}

	// Extract session ID from context for authenticated operations
	var sessionID uuid.UUID
	if sid := ctx.Get("sessionID"); sid != nil {
		sessionID = sid.(uuid.UUID)
	} else {
		return echo.NewHTTPError(http.StatusUnauthorized, "session required")
	}

	// Query parameters
	var params ListLabelsParams
	// Optional query parameter "Filter"
	if err := runtime.BindQueryParameter("deepObject", true, false, "filter", ctx.QueryParams(), &params.Filter); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter filter: %s", err))
	}
	// Optional query parameter "Page"
	if err := runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}
	// Optional query parameter "Sort"
	if err := runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}
	request.Params = params

	// Set auth scopes
	ctx.Set(server.BearerAuthScopes, []string{})

	// Determine which handler to call based on operation
	// Query handler
	query := queries.NewListLabelsQuery(
		sessionID, // SessionID for authenticated operations
	)
	// TODO: Apply filters, pagination, sorting from request.Params

	results, total, err := c.listLabelsHandler.Handle(reqCtx, query)
	if err != nil {
		return err
	}

	return ctx.JSON(http.StatusOK, map[string]interface{}{
		"data": results,
		"meta": map[string]interface{}{
			"total": total,
		},
	})
}

// ============================================================================
// UpdateLabel - PATCH /labels/{id}
// ============================================================================

// Request types
// UpdateLabelRequestBody defines the request body for UpdateLabel
type UpdateLabelRequestBody struct {
	Name *string `json:"name,omitempty"`
}

type UpdateLabelRequest struct {
	ID   uuid.UUID `json:"id"`
	Body *UpdateLabelRequestBody
}

// Response types

type UpdateLabelResponse interface {
	VisitUpdateLabelResponse(w http.ResponseWriter) error
}

type UpdateLabel200Response struct {
	Data entities.Label `json:"data"`
}

func (response UpdateLabel200Response) VisitUpdateLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateLabel404Response struct {
	server.NotFoundResponse
}

func (response UpdateLabel404Response) VisitUpdateLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.NotFoundResponse)
}

// Handler method

// UpdateLabel handles the PATCH /labels/{id} endpoint.
func (c *LabelController) UpdateLabel(ctx echo.Context) error {
	reqCtx := ctx.Request().Context()
	request := UpdateLabelRequest{}

	// Extract session ID from context for authenticated operations
	var sessionID uuid.UUID
	if sid := ctx.Get("sessionID"); sid != nil {
		sessionID = sid.(uuid.UUID)
	} else {
		return echo.NewHTTPError(http.StatusUnauthorized, "session required")
	}

	// Path parameter "id"
	var id uuid.UUID
	if err := runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true}); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}
	request.ID = id

	// Request body
	request.Body = &UpdateLabelRequestBody{}
	if err := ctx.Bind(request.Body); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}

	// Set auth scopes
	ctx.Set(server.BearerAuthScopes, []string{})

	// Determine which handler to call based on operation
	// Command handler

	// Map request to command parameters
	cmd := commands.NewUpdateLabelCommand(
		sessionID,         // SessionID for authenticated operations
		request.ID,        // ID
		request.Body.Name, // Name
	)
	result, err := c.updateLabelHandler.Handle(reqCtx, cmd)
	if err != nil {
		return err
	}
	return ctx.JSON(http.StatusOK, map[string]interface{}{
		"data": result,
	})
}

// ============================================================================
// DeleteLabel - DELETE /labels/{id}
// ============================================================================

// Request types

type DeleteLabelRequest struct {
	ID uuid.UUID `json:"id"`
}

// Response types

type DeleteLabelResponse interface {
	VisitDeleteLabelResponse(w http.ResponseWriter) error
}

type DeleteLabel200Response struct {
	Data entities.Label `json:"data"`
}

func (response DeleteLabel200Response) VisitDeleteLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteLabel404Response struct {
	server.NotFoundResponse
}

func (response DeleteLabel404Response) VisitDeleteLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.NotFoundResponse)
}

// Handler method

// DeleteLabel handles the DELETE /labels/{id} endpoint.
func (c *LabelController) DeleteLabel(ctx echo.Context) error {
	reqCtx := ctx.Request().Context()
	request := DeleteLabelRequest{}

	// Extract session ID from context for authenticated operations
	var sessionID uuid.UUID
	if sid := ctx.Get("sessionID"); sid != nil {
		sessionID = sid.(uuid.UUID)
	} else {
		return echo.NewHTTPError(http.StatusUnauthorized, "session required")
	}

	// Path parameter "id"
	var id uuid.UUID
	if err := runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true}); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}
	request.ID = id

	// Set auth scopes
	ctx.Set(server.BearerAuthScopes, []string{})

	// Determine which handler to call based on operation
	// Command handler

	// Map request to command parameters
	cmd := commands.NewDeleteLabelCommand(
		sessionID,  // SessionID for authenticated operations
		request.ID, // ID
	)
	if err := c.deleteLabelHandler.Handle(reqCtx, cmd); err != nil {
		return err
	}
	return ctx.NoContent(http.StatusNoContent)
}
