// Code generated by archesai codegen. DO NOT EDIT.
package controllers

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"

	"github.com/archesai/archesai/internal/adapters/http/server"
	commands "github.com/archesai/archesai/internal/application/commands/organizations"
	queries "github.com/archesai/archesai/internal/application/queries/organizations"
)

// OrganizationsController handles HTTP requests for organizations endpoints.
type OrganizationsController struct {
	// Command handlers
	createHandler *commands.CreateOrganizationCommandHandler
	updateHandler *commands.UpdateOrganizationCommandHandler
	deleteHandler *commands.DeleteOrganizationCommandHandler
	// Query handlers
	getHandler  *queries.GetOrganizationQueryHandler
	listHandler *queries.ListOrganizationsQueryHandler
}

// NewOrganizationsController creates a new organizations controller with injected handlers.
func NewOrganizationsController(
	createHandler *commands.CreateOrganizationCommandHandler,
	updateHandler *commands.UpdateOrganizationCommandHandler,
	deleteHandler *commands.DeleteOrganizationCommandHandler,
	getHandler *queries.GetOrganizationQueryHandler,
	listHandler *queries.ListOrganizationsQueryHandler,
) *OrganizationsController {
	return &OrganizationsController{
		createHandler: createHandler,
		updateHandler: updateHandler,
		deleteHandler: deleteHandler,
		getHandler:    getHandler,
		listHandler:   listHandler,
	}
}

// RegisterOrganizationsRoutes registers all HTTP routes for the organizations domain.
func RegisterOrganizationsRoutes(router server.EchoRouter, controller *OrganizationsController) {
	router.POST("/organizations", controller.CreateOrganization)
	router.GET("/organizations", controller.ListOrganizations)
	router.DELETE("/organizations/:id", controller.DeleteOrganization)
	router.GET("/organizations/:id", controller.GetOrganization)
	router.PATCH("/organizations/:id", controller.UpdateOrganization)
}

// ============================================================================
// CreateOrganization - POST /organizations
// ============================================================================

// Request types
// CreateOrganizationRequestBody defines the request body for CreateOrganization
type CreateOrganizationRequestBody struct {
	BillingEmail   string    `json:"billingEmail"`
	OrganizationID uuid.UUID `json:"organizationID"`
}

type CreateOrganizationRequest struct {
	Body *CreateOrganizationRequestBody
}

// Response types

type CreateOrganizationResponse interface {
	VisitCreateOrganizationResponse(w http.ResponseWriter) error
}

type CreateOrganization201JSONResponse struct {
}

func (response CreateOrganization201JSONResponse) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrganization400Response struct {
	server.BadRequestResponse
}

func (response CreateOrganization400Response) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.BadRequestResponse)
}

type CreateOrganization401Response struct {
	server.UnauthorizedResponse
}

func (response CreateOrganization401Response) VisitCreateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.UnauthorizedResponse)
}

// Handler method

// CreateOrganization handles the POST /organizations endpoint.
func (c *OrganizationsController) CreateOrganization(ctx echo.Context) error {
	reqCtx := ctx.Request().Context()
	request := CreateOrganizationRequest{}

	// Request body
	var body CreateOrganizationRequestBody
	if err := ctx.Bind(&body); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}
	request.Body = &body

	// Determine which handler to call based on operation
	// Create handler
	// Available request body fields: BillingEmail, OrganizationID

	// TODO: Get organization ID from auth context
	orgID := uuid.New()

	// Create command - adjust field mapping based on your API
	cmd := commands.NewCreateOrganizationCommand(
		orgID,
		"",  // TODO: Map appropriate field from request.Body
		"",  // TODO: Map appropriate field from request.Body
		nil, // TODO: Map metadata if available
	)

	result, err := c.createHandler.Handle(reqCtx, cmd)
	if err != nil {
		return err
	}

	return ctx.JSON(http.StatusCreated, map[string]interface{}{
		"data": result,
	})
}

// ============================================================================
// ListOrganizations - GET /organizations
// ============================================================================

// Request types
// ListOrganizationsParams defines parameters for ListOrganizations
type ListOrganizationsParams struct {
	Filter *map[string]interface{}   `json:"filter,omitempty"`
	Page   *map[string]interface{}   `json:"page,omitempty"`
	Sort   *[]map[string]interface{} `json:"sort,omitempty"`
}

type ListOrganizationsRequest struct {
	Params ListOrganizationsParams
}

// Response types

type ListOrganizationsResponse interface {
	VisitListOrganizationsResponse(w http.ResponseWriter) error
}

type ListOrganizations200JSONResponse struct {
}

func (response ListOrganizations200JSONResponse) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListOrganizations400Response struct {
	server.BadRequestResponse
}

func (response ListOrganizations400Response) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response.BadRequestResponse)
}

type ListOrganizations401Response struct {
	server.UnauthorizedResponse
}

func (response ListOrganizations401Response) VisitListOrganizationsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.UnauthorizedResponse)
}

// Handler method

// ListOrganizations handles the GET /organizations endpoint.
func (c *OrganizationsController) ListOrganizations(ctx echo.Context) error {
	reqCtx := ctx.Request().Context()
	request := ListOrganizationsRequest{}

	// Query parameters
	var params ListOrganizationsParams
	// Optional query parameter "filter"
	if err := runtime.BindQueryParameter("deepObject", true, false, "filter", ctx.QueryParams(), &params.Filter); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter filter: %s", err))
	}
	// Optional query parameter "page"
	if err := runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}
	// Optional query parameter "sort"
	if err := runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}
	request.Params = params

	// Determine which handler to call based on operation
	// Create list query from request
	query := queries.NewListOrganizationsQuery()
	// TODO: Apply filters, pagination, sorting from request.Params

	results, total, err := c.listHandler.Handle(reqCtx, query)
	if err != nil {
		return err
	}

	return ctx.JSON(http.StatusOK, map[string]interface{}{
		"data": results,
		"meta": map[string]interface{}{
			"total": total,
		},
	})
}

// ============================================================================
// DeleteOrganization - DELETE /organizations/{id}
// ============================================================================

// Request types

type DeleteOrganizationRequest struct {
	ID uuid.UUID `json:"id"`
}

// Response types

type DeleteOrganizationResponse interface {
	VisitDeleteOrganizationResponse(w http.ResponseWriter) error
}

type DeleteOrganization200JSONResponse struct {
}

func (response DeleteOrganization200JSONResponse) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrganization404Response struct {
	server.NotFoundResponse
}

func (response DeleteOrganization404Response) VisitDeleteOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.NotFoundResponse)
}

// Handler method

// DeleteOrganization handles the DELETE /organizations/{id} endpoint.
func (c *OrganizationsController) DeleteOrganization(ctx echo.Context) error {
	reqCtx := ctx.Request().Context()
	request := DeleteOrganizationRequest{}

	// Path parameter "id"
	var id uuid.UUID
	if err := runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true}); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}
	request.ID = id

	// Determine which handler to call based on operation
	// Create delete command from request
	cmd := commands.NewDeleteOrganizationCommand(
		request.ID,
	)

	err := c.deleteHandler.Handle(reqCtx, cmd)
	if err != nil {
		return err
	}

	return ctx.NoContent(http.StatusNoContent)
}

// ============================================================================
// GetOrganization - GET /organizations/{id}
// ============================================================================

// Request types

type GetOrganizationRequest struct {
	ID uuid.UUID `json:"id"`
}

// Response types

type GetOrganizationResponse interface {
	VisitGetOrganizationResponse(w http.ResponseWriter) error
}

type GetOrganization200JSONResponse struct {
}

func (response GetOrganization200JSONResponse) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOrganization404Response struct {
	server.NotFoundResponse
}

func (response GetOrganization404Response) VisitGetOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.NotFoundResponse)
}

// Handler method

// GetOrganization handles the GET /organizations/{id} endpoint.
func (c *OrganizationsController) GetOrganization(ctx echo.Context) error {
	reqCtx := ctx.Request().Context()
	request := GetOrganizationRequest{}

	// Path parameter "id"
	var id uuid.UUID
	if err := runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true}); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}
	request.ID = id

	// Determine which handler to call based on operation
	// Create get query from request
	query := queries.NewGetOrganizationQuery(
		request.ID,
	)

	result, err := c.getHandler.Handle(reqCtx, query)
	if err != nil {
		return err
	}

	return ctx.JSON(http.StatusOK, map[string]interface{}{
		"data": result,
	})
}

// ============================================================================
// UpdateOrganization - PATCH /organizations/{id}
// ============================================================================

// Request types
// UpdateOrganizationRequestBody defines the request body for UpdateOrganization
type UpdateOrganizationRequestBody struct {
	BillingEmail   *string    `json:"billingEmail,omitempty"`
	OrganizationID *uuid.UUID `json:"organizationID,omitempty"`
}

type UpdateOrganizationRequest struct {
	ID   uuid.UUID `json:"id"`
	Body *UpdateOrganizationRequestBody
}

// Response types

type UpdateOrganizationResponse interface {
	VisitUpdateOrganizationResponse(w http.ResponseWriter) error
}

type UpdateOrganization200JSONResponse struct {
}

func (response UpdateOrganization200JSONResponse) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrganization404Response struct {
	server.NotFoundResponse
}

func (response UpdateOrganization404Response) VisitUpdateOrganizationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response.NotFoundResponse)
}

// Handler method

// UpdateOrganization handles the PATCH /organizations/{id} endpoint.
func (c *OrganizationsController) UpdateOrganization(ctx echo.Context) error {
	reqCtx := ctx.Request().Context()
	request := UpdateOrganizationRequest{}

	// Path parameter "id"
	var id uuid.UUID
	if err := runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true}); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}
	request.ID = id

	// Request body
	var body UpdateOrganizationRequestBody
	if err := ctx.Bind(&body); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}
	request.Body = &body

	// Determine which handler to call based on operation
	// Update handler
	// Available request body fields: BillingEmail, OrganizationID

	// Create update command - adjust field mapping based on your API
	cmd := commands.NewUpdateOrganizationCommand(
		request.ID, // Assumes all update operations have an ID path parameter
		nil,        // TODO: Map appropriate field from request.Body
		nil,        // TODO: Map appropriate field from request.Body
		nil,        // TODO: Map metadata if available
	)

	result, err := c.updateHandler.Handle(reqCtx, cmd)
	if err != nil {
		return err
	}

	return ctx.JSON(http.StatusOK, map[string]interface{}{
		"data": result,
	})
}
