// Code generated by archesai. DO NOT EDIT.

package http

import (
	"errors"
	"log/slog"
	"net/http"

	"github.com/google/uuid"

	"github.com/archesai/archesai/pkg/auth/operations"
	"github.com/archesai/archesai/pkg/httputil"
	"github.com/archesai/archesai/pkg/server"
)

// ============================================================================
// DeleteAPIKey - DELETE /api-keys/{id}
// ============================================================================

// DeleteAPIKeyHandler is the HTTP handler for DeleteAPIKey.
type DeleteAPIKeyHandler struct {
	deleteAPIKey operations.DeleteAPIKey
}

// NewDeleteAPIKeyHandler creates a new HTTP handler.
func NewDeleteAPIKeyHandler(deleteAPIKey operations.DeleteAPIKey) *DeleteAPIKeyHandler {
	return &DeleteAPIKeyHandler{deleteAPIKey: deleteAPIKey}
}

// RegisterDeleteAPIKeyRoute registers the HTTP route for DeleteAPIKey.
func RegisterDeleteAPIKeyRoute(mux *http.ServeMux, handler *DeleteAPIKeyHandler) {
	mux.HandleFunc("DELETE /api-keys/{id}", handler.ServeHTTP)
}

// Response Types

// DeleteAPIKey400Response is the 400 error response.
type DeleteAPIKey400Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (DeleteAPIKey400Response) StatusCode() int { return 400 }

// DeleteAPIKey401Response is the 401 error response.
type DeleteAPIKey401Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (DeleteAPIKey401Response) StatusCode() int { return 401 }

// DeleteAPIKey404Response is the 404 error response.
type DeleteAPIKey404Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (DeleteAPIKey404Response) StatusCode() int { return 404 }

// DeleteAPIKey422Response is the 422 error response.
type DeleteAPIKey422Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (DeleteAPIKey422Response) StatusCode() int { return 422 }

// DeleteAPIKey429Response is the 429 error response.
type DeleteAPIKey429Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (DeleteAPIKey429Response) StatusCode() int { return 429 }

// DeleteAPIKey500Response is the 500 error response.
type DeleteAPIKey500Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (DeleteAPIKey500Response) StatusCode() int { return 500 }

// ServeHTTP handles the DELETE /api-keys/{id} endpoint.
func (h *DeleteAPIKeyHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Extract session ID from context for authenticated operations
	sessionID, ok := ctx.Value(server.SessionIDContextKey).(uuid.UUID)
	if !ok {
		_ = httputil.WriteResponse(w, DeleteAPIKey401Response{
			ProblemDetails: httputil.NewUnauthorizedResponse("session required", r.URL.Path),
		})
		return
	}

	// Build input from request
	input := &operations.DeleteAPIKeyInput{}
	input.SessionID = sessionID

	// Path parameter "id"
	if err := httputil.BindPathParam(r, "id", &input.ID); err != nil {
		_ = httputil.WriteResponse(w, DeleteAPIKey400Response{
			ProblemDetails: httputil.NewBadRequestResponse(err.Error(), r.URL.Path),
		})
		return
	}

	// Execute handler
	if err := h.deleteAPIKey.Execute(ctx, input); err != nil {
		var httpErr httputil.HTTPError
		if errors.As(err, &httpErr) {
			_ = httputil.WriteHTTPError(w, httpErr, r.URL.Path)
			return
		}
		slog.Error("handler error", "operation", "DeleteAPIKey", "error", err)
		_ = httputil.WriteResponse(w, DeleteAPIKey500Response{
			ProblemDetails: httputil.NewInternalServerErrorResponse(err.Error(), r.URL.Path),
		})
		return
	}
	httputil.WriteNoContent(w)
}
