// Code generated by archesai/codegen. DO NOT EDIT.

package tools

import (
	"context"
	"time"

	"github.com/archesai/archesai/internal/core/entities"
	"github.com/archesai/archesai/internal/core/errors"
	"github.com/archesai/archesai/internal/core/events"
	"github.com/archesai/archesai/internal/core/repositories"
	"github.com/archesai/archesai/internal/core/valueobjects"
	"github.com/archesai/archesai/internal/infrastructure/events"
)

// CreateToolCommand represents the command to create a tool.
type CreateToolCommand struct {
	OrganizationID valueobjects.OrganizationID
	Name           string
	Description    string
	Metadata       map[string]interface{}
}

// NewCreateToolCommand creates a new create tool command.
func NewCreateToolCommand(
	organizationID valueobjects.OrganizationID,
	name string,
	description string,
	metadata map[string]interface{},
) *CreateToolCommand {
	return &CreateToolCommand{
		OrganizationID: organizationID,
		Name:           name,
		Description:    description,
		Metadata:       metadata,
	}
}

// CreateToolCommandHandler handles the create tool command.
type CreateToolCommandHandler struct {
	repo      repositories.ToolRepository
	publisher events.Publisher
}

// NewCreateToolCommandHandler creates a new create tool command handler.
func NewCreateToolCommandHandler(
	repo repositories.ToolRepository,
	publisher events.Publisher,
) *CreateToolCommandHandler {
	return &CreateToolCommandHandler{
		repo:      repo,
		publisher: publisher,
	}
}

// Handle executes the create tool command.
func (h *CreateToolCommandHandler) Handle(ctx context.Context, cmd *CreateToolCommand) (*entities.Tool, error) {
	// Create the tool entity
	entity := &entities.Tool{
		ID:        valueobjects.NewToolID(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		// TODO: Map command fields to entity
	}

	// Save to repository
	created, err := h.repo.Create(ctx, entity)
	if err != nil {
		return nil, errors.Wrap(err, "failed to create tool")
	}

	// Publish domain event
	event := events.NewToolCreatedEvent(
		created.ID,
		created.CreatedAt,
	)
	if err := h.publisher.Publish(ctx, event); err != nil {
		// Log error but don't fail the operation
	}

	return created, nil
}
