// Code generated by codegen repository. DO NOT EDIT.
package repositories

import (
	"context"

	"github.com/archesai/archesai/internal/core/entities"
	"github.com/google/uuid"
)

// OrganizationRepository handles organization persistence
type OrganizationRepository interface {
	// Basic CRUD operations (always included)
	Create(ctx context.Context, entity *entities.Organization) (*entities.Organization, error)
	Get(ctx context.Context, id uuid.UUID) (*entities.Organization, error)
	Update(ctx context.Context, id uuid.UUID, entity *entities.Organization) (*entities.Organization, error)
	Delete(ctx context.Context, id uuid.UUID) error
	List(ctx context.Context, limit, offset int32) ([]*entities.Organization, int64, error)

	// Additional operations
	// GetOrganizationBySlug retrieves a single organization by slug
	GetOrganizationBySlug(ctx context.Context, slug string) (*entities.Organization, error)
	// GetOrganizationByStripeCustomerID retrieves a single organization by stripeCustomerIdentifier
	GetOrganizationByStripeCustomerID(ctx context.Context, stripeCustomerIdentifier string) (*entities.Organization, error)
}
