// Code generated by archesai. DO NOT EDIT.

package repositories

import (
	"context"

	"github.com/archesai/archesai/internal/core/entities"
	"github.com/google/uuid"
)

// PipelineRepository handles pipeline persistence
type PipelineRepository interface {
	// Basic CRUD operations (always included)
	Create(ctx context.Context, entity *entities.Pipeline) (*entities.Pipeline, error)
	Get(ctx context.Context, id uuid.UUID) (*entities.Pipeline, error)
	Update(ctx context.Context, id uuid.UUID, entity *entities.Pipeline) (*entities.Pipeline, error)
	Delete(ctx context.Context, id uuid.UUID) error
	List(ctx context.Context, limit, offset int32) ([]*entities.Pipeline, int64, error)

	// ListPipelinesByOrganization retrieves multiple pipelines by organizationID
	ListPipelinesByOrganization(ctx context.Context, organizationID string) ([]*entities.Pipeline, error)
}
