// Code generated by archesai/codegen. DO NOT EDIT.

package auth

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/archesai/archesai/internal/core/entities"
	"github.com/archesai/archesai/internal/core/repositories"
)

// ListSessionsQuery represents a query to list sessions.
type ListSessionsQuery struct {
	SessionID      uuid.UUID
	Limit          int32
	Offset         int32
	OrderBy        string
	OrderDirection string
}

// NewListSessionsQuery creates a new list sessions query.
func NewListSessionsQuery(
	SessionID uuid.UUID,
) *ListSessionsQuery {
	return &ListSessionsQuery{
		SessionID: SessionID,
		Limit:     100,
		Offset:    0,
	}
}

// ListSessionsQueryHandler handles the list sessions query.
type ListSessionsQueryHandler struct {
	repo repositories.SessionRepository
}

// NewListSessionsQueryHandler creates a new list sessions query handler.
func NewListSessionsQueryHandler(repo repositories.SessionRepository) *ListSessionsQueryHandler {
	return &ListSessionsQueryHandler{
		repo: repo,
	}
}

// Handle executes the list sessions query.
func (h *ListSessionsQueryHandler) Handle(ctx context.Context, query *ListSessionsQuery) ([]*entities.Session, int64, error) {
	// TODO: Apply filters based on query parameters
	results, total, err := h.repo.List(ctx, query.Limit, query.Offset)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to list sessions: %w", err)
	}

	return results, total, nil
}
