// Code generated by archesai/codegen. DO NOT EDIT.

package members

import (
	"context"
	"time"

	"github.com/archesai/archesai/internal/core/entities"
	"github.com/archesai/archesai/internal/core/errors"
	"github.com/archesai/archesai/internal/core/events"
	"github.com/archesai/archesai/internal/core/repositories"
	"github.com/archesai/archesai/internal/core/valueobjects"
	"github.com/archesai/archesai/internal/infrastructure/events"
)

// CreateMemberCommand represents the command to create a member.
type CreateMemberCommand struct {
	OrganizationID valueobjects.OrganizationID
	Name           string
	Description    string
	Metadata       map[string]interface{}
}

// NewCreateMemberCommand creates a new create member command.
func NewCreateMemberCommand(
	organizationID valueobjects.OrganizationID,
	name string,
	description string,
	metadata map[string]interface{},
) *CreateMemberCommand {
	return &CreateMemberCommand{
		OrganizationID: organizationID,
		Name:           name,
		Description:    description,
		Metadata:       metadata,
	}
}

// CreateMemberCommandHandler handles the create member command.
type CreateMemberCommandHandler struct {
	repo      repositories.MemberRepository
	publisher events.Publisher
}

// NewCreateMemberCommandHandler creates a new create member command handler.
func NewCreateMemberCommandHandler(
	repo repositories.MemberRepository,
	publisher events.Publisher,
) *CreateMemberCommandHandler {
	return &CreateMemberCommandHandler{
		repo:      repo,
		publisher: publisher,
	}
}

// Handle executes the create member command.
func (h *CreateMemberCommandHandler) Handle(ctx context.Context, cmd *CreateMemberCommand) (*entities.Member, error) {
	// Create the member entity
	entity := &entities.Member{
		ID:        valueobjects.NewMemberID(),
		CreatedAt: time.Now().UTC(),
		UpdatedAt: time.Now().UTC(),
		// TODO: Map command fields to entity
	}

	// Save to repository
	created, err := h.repo.Create(ctx, entity)
	if err != nil {
		return nil, errors.Wrap(err, "failed to create member")
	}

	// Publish domain event
	event := events.NewMemberCreatedEvent(
		created.ID,
		created.CreatedAt,
	)
	if err := h.publisher.Publish(ctx, event); err != nil {
		// Log error but don't fail the operation
	}

	return created, nil
}
