// Code generated by archesai. DO NOT EDIT.

package application

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/archesai/archesai/pkg/auth/models"
	"github.com/archesai/archesai/pkg/auth/repositories"
)

// ============================================================================
// GetAccount Handler
// ============================================================================

// GetAccountInput represents the input for the GetAccount operation.
type GetAccountInput struct {
	SessionID uuid.UUID
	ID        uuid.UUID
}

// GetAccountOutput represents the output for the GetAccount operation.
type GetAccountOutput struct {
	Data models.Account `json:"data"`
}

// GetAccountHandler defines the interface for the GetAccount operation.
type GetAccountHandler interface {
	Execute(ctx context.Context, input *GetAccountInput) (*GetAccountOutput, error)
}

// GetAccountHandlerImpl is the default implementation of GetAccountHandler.
type GetAccountHandlerImpl struct {
	repo repositories.AccountRepository
}

// NewGetAccountHandler creates a new GetAccount handler.
func NewGetAccountHandler(
	repo repositories.AccountRepository,
) GetAccountHandler {
	return &GetAccountHandlerImpl{
		repo: repo,
	}
}

// Execute performs the GetAccount operation.
func (h *GetAccountHandlerImpl) Execute(ctx context.Context, input *GetAccountInput) (*GetAccountOutput, error) {
	// Get from repository
	result, err := h.repo.Get(ctx, input.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get auth: %w", err)
	}

	// Map to output
	output := &GetAccountOutput{
		// TODO: Map result fields to output
	}
	_ = result

	return output, nil
}
