// Code generated by archesai. DO NOT EDIT.

package application

import (
	"context"

	"github.com/google/uuid"
)

// ============================================================================
// OauthAuthorize Handler
// ============================================================================

// OauthAuthorizeInput represents the input for the OauthAuthorize operation.
type OauthAuthorizeInput struct {
	SessionID   uuid.UUID
	Provider    string
	RedirectURI *string
	Scope       *string
	State       *string
}

// OauthAuthorizeOutput represents the output for the OauthAuthorize operation.
type OauthAuthorizeOutput struct {
	AuthorizationURL string `json:"authorizationURL"`
}

// OauthAuthorizeHandler defines the interface for the OauthAuthorize operation.
type OauthAuthorizeHandler interface {
	Execute(ctx context.Context, input *OauthAuthorizeInput) (*OauthAuthorizeOutput, error)
}
