// Code generated by archesai. DO NOT EDIT.

package invitation

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/archesai/archesai/internal/core/models"
	"github.com/archesai/archesai/internal/core/repositories"
)

// ListInvitationsQuery represents a query to get invitation.
type ListInvitationsQuery struct {
	SessionID      uuid.UUID
	OrganizationID uuid.UUID
}

// NewListInvitationsQuery creates a new get invitation query.
func NewListInvitationsQuery(
	SessionID uuid.UUID,
	OrganizationID uuid.UUID,
) *ListInvitationsQuery {
	return &ListInvitationsQuery{
		SessionID:      SessionID,
		OrganizationID: OrganizationID,
	}
}

// ListInvitationsQueryHandler handles the get invitation query.
type ListInvitationsQueryHandler struct {
	repo repositories.InvitationRepository
}

// NewListInvitationsQueryHandler creates a new get invitation query handler.
func NewListInvitationsQueryHandler(repo repositories.InvitationRepository) *ListInvitationsQueryHandler {
	return &ListInvitationsQueryHandler{
		repo: repo,
	}
}

// Handle executes the list invitations query.
func (h *ListInvitationsQueryHandler) Handle(ctx context.Context, query *ListInvitationsQuery) ([]*models.Invitation, int64, error) {
	// TODO: Apply filters based on query parameters
	results, total, err := h.repo.List(ctx, 100, 0)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to list invitations: %w", err)
	}

	return results, total, nil
}
