package strutil

// Common acronyms that should be preserved in uppercase
var commonAcronyms = map[string]string{
	"api":   "API",
	"url":   "URL",
	"uri":   "URI",
	"uuid":  "UUID",
	"id":    "ID",
	"http":  "HTTP",
	"https": "HTTPS",
	"sql":   "SQL",
	"json":  "JSON",
	"xml":   "XML",
	"csv":   "CSV",
	"jwt":   "JWT",
	"oauth": "OAuth",
	"saml":  "SAML",
	"ldap":  "LDAP",
	"dns":   "DNS",
	"tcp":   "TCP",
	"udp":   "UDP",
	"ip":    "IP",
	"vm":    "VM",
	"os":    "OS",
	"cpu":   "CPU",
	"gpu":   "GPU",
	"ram":   "RAM",
	"ssd":   "SSD",
	"hdd":   "HDD",
	"cdn":   "CDN",
	"vpn":   "VPN",
	"ssh":   "SSH",
	"ftp":   "FTP",
	"sftp":  "SFTP",
	"smtp":  "SMTP",
	"imap":  "IMAP",
	"pop":   "POP",
	"aws":   "AWS",
	"gcp":   "GCP",
	"sdk":   "SDK",
	"ci":    "CI",
	"cd":    "CD",
}
