// Code generated by archesai. DO NOT EDIT.

package operations

import (
	"context"
	"fmt"

	"github.com/archesai/archesai/pkg/auth/schemas"
	"github.com/archesai/archesai/pkg/events"
	"github.com/archesai/archesai/pkg/executor"
	"github.com/google/uuid"
)

// ============================================================================
// DeleteUser
// ============================================================================

// DeleteUserInput represents the input for the DeleteUser operation.
type DeleteUserInput struct {
	SessionID uuid.UUID
	ID        uuid.UUID
}

// DeleteUser defines the executor interface for the DeleteUser operation.
type DeleteUser = executor.VoidExecutor[DeleteUserInput]

// DeleteUserImpl is the default implementation of DeleteUser.
type DeleteUserImpl struct {
	repo      schemas.UserRepository
	publisher events.Publisher
}

// NewDeleteUser creates a new DeleteUser handler.
func NewDeleteUser(
	repo schemas.UserRepository,
	publisher events.Publisher,
) DeleteUser {
	return &DeleteUserImpl{
		repo:      repo,
		publisher: publisher,
	}
}

// Execute performs the DeleteUser operation.
func (h *DeleteUserImpl) Execute(ctx context.Context, input *DeleteUserInput) error {
	// Delete from repository
	if err := h.repo.Delete(ctx, input.ID); err != nil {
		return fmt.Errorf("failed to delete user: %w", err)
	}

	// Publish domain event
	event := schemas.NewUserDeletedEvent(input.ID)
	_ = h.publisher.Publish(ctx, event)

	return nil
}
