// Code generated by archesai/codegen. DO NOT EDIT.

package organizations

import (
	"context"
	"errors"
	"log/slog"
	"time"

	"github.com/archesai/archesai/internal/database/postgresql"
	"github.com/google/uuid"
)

// Service implements the business logic
type Service struct {
	repo   Repository
	db     *postgresql.Queries
	logger *slog.Logger
}

// NewService creates a new service implementation
func NewService(repo Repository, db *postgresql.Queries, logger *slog.Logger) *Service {
	return &Service{
		repo:   repo,
		db:     db,
		logger: logger,
	}
}

// CreateOrganization creates a new organization
func (s *Service) CreateOrganization(ctx context.Context, entity *Organization) (*Organization, error) {
	if entity == nil {
		return nil, errors.New("entity is required")
	}

	// Set timestamps if not already set
	if entity.CreatedAt.IsZero() {
		entity.CreatedAt = time.Now()
	}
	if entity.UpdatedAt.IsZero() {
		entity.UpdatedAt = time.Now()
	}

	created, err := s.repo.Create(ctx, entity)
	if err != nil {
		s.logger.Error("Failed to create organization", "error", err)
		return nil, err
	}

	return created, nil
}

// GetOrganization gets a organization by ID
func (s *Service) GetOrganization(ctx context.Context, id uuid.UUID) (*Organization, error) {
	entity, err := s.repo.Get(ctx, id)
	if err != nil {
		if errors.Is(err, ErrOrganizationNotFound) {
			return nil, err
		}
		s.logger.Error("Failed to get organization", "error", err, "id", id)
		return nil, err
	}

	return entity, nil
}

// UpdateOrganization updates a organization
func (s *Service) UpdateOrganization(ctx context.Context, id uuid.UUID, entity *Organization) (*Organization, error) {
	if entity == nil {
		return nil, errors.New("entity is required")
	}

	// Set updated timestamp
	entity.UpdatedAt = time.Now()

	updated, err := s.repo.Update(ctx, id, entity)
	if err != nil {
		s.logger.Error("Failed to update organization", "error", err, "id", id)
		return nil, err
	}

	return updated, nil
}

// DeleteOrganization deletes a organization
func (s *Service) DeleteOrganization(ctx context.Context, id uuid.UUID) error {
	// Check if entity exists first
	_, err := s.repo.Get(ctx, id)
	if err != nil {
		if errors.Is(err, ErrOrganizationNotFound) {
			return err
		}
		s.logger.Error("Failed to get organization for deletion", "error", err, "id", id)
		return err
	}

	err = s.repo.Delete(ctx, id)
	if err != nil {
		s.logger.Error("Failed to delete organization", "error", err, "id", id)
		return err
	}

	return nil
}

// ListOrganizations lists all organizations
func (s *Service) ListOrganizations(ctx context.Context, filter *ListOrganizationsParamsFilter, page *ListOrganizationsParamsPage, sort *ListOrganizationsParamsSort) ([]*Organization, int64, error) {
	params := ListOrganizationsParams{
		Filter: filter,
		Page:   page,
		Sort:   sort,
	}
	entities, total, err := s.repo.List(ctx, params)
	if err != nil {
		s.logger.Error("Failed to list organizations", "error", err)
		return nil, 0, err
	}

	return entities, total, nil
}
