// Code generated by archesai/codegen. DO NOT EDIT.

package dto

import (
	"time"

	"github.com/google/uuid"
)

// Base represents a Base
type Base struct {
	CreatedAt time.Time
	ID        uuid.UUID
	UpdatedAt time.Time
}
