// Code generated by archesai/codegen. DO NOT EDIT.

package dto

// ConfigInfrastructure represents a ConfigInfrastructure
type ConfigInfrastructure struct {
	Images         ConfigImages
	Migrations     ConfigMigrations
	Namespace      string
	ServiceAccount ConfigServiceAccount
}
