// Code generated by archesai/codegen. DO NOT EDIT.

package dto

// ConfigAuthMagicLink represents a ConfigAuthMagicLink
type ConfigAuthMagicLink struct {
	DeliveryMethods *interface{}
	Enabled         bool
	OtpLength       *int
	RateLimit       *interface{}
	TokenExpiry     *int
}
