// Code generated by archesai. DO NOT EDIT.

package routes

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"

	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"

	"github.com/archesai/archesai/pkg/auth/handlers"
	"github.com/archesai/archesai/pkg/auth/models"
	"github.com/archesai/archesai/pkg/server"
	servermodels "github.com/archesai/archesai/pkg/server/models"
)

// ============================================================================
// ListAccounts - GET /auth/accounts
// ============================================================================

// ListAccountsHandler is the HTTP handler for ListAccounts.
type ListAccountsHandler struct {
	listAccounts handlers.ListAccounts
}

// NewListAccountsHandler creates a new HTTP handler.
func NewListAccountsHandler(listAccounts handlers.ListAccounts) *ListAccountsHandler {
	return &ListAccountsHandler{listAccounts: listAccounts}
}

// RegisterListAccountsRoute registers the HTTP route for ListAccounts.
func RegisterListAccountsRoute(mux *http.ServeMux, handler *ListAccountsHandler) {
	mux.HandleFunc("GET /auth/accounts", handler.ServeHTTP)
}

// Request types

// ListAccountsParams defines query parameters for ListAccounts
type ListAccountsParams struct {
	AccountsFilter *servermodels.FilterNode `json:"accountsFilter"`
	AccountsSort   *servermodels.FilterNode `json:"accountsSort"`
	Page           servermodels.Page        `json:"page"`
}

// Response types

type ListAccountsResponse interface {
	VisitListAccountsResponse(w http.ResponseWriter) error
}

type ListAccounts200Response struct {
	Data []models.Account            `json:"data"`
	Meta servermodels.PaginationMeta `json:"meta"`
}

func (response ListAccounts200Response) VisitListAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	return json.NewEncoder(w).Encode(response)
}

type ListAccounts400Response struct {
	server.ProblemDetails
}

func (response ListAccounts400Response) VisitListAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type ListAccounts401Response struct {
	server.ProblemDetails
}

func (response ListAccounts401Response) VisitListAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type ListAccounts422Response struct {
	server.ProblemDetails
}

func (response ListAccounts422Response) VisitListAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type ListAccounts429Response struct {
	server.ProblemDetails
}

func (response ListAccounts429Response) VisitListAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type ListAccounts500Response struct {
	server.ProblemDetails
}

func (response ListAccounts500Response) VisitListAccountsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

// ServeHTTP handles the GET /auth/accounts endpoint.
func (h *ListAccountsHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Extract session ID from context for authenticated operations
	sessionID, ok := ctx.Value(server.SessionIDContextKey).(uuid.UUID)
	if !ok {
		errorResp := ListAccounts401Response{
			ProblemDetails: server.NewUnauthorizedResponse("session required", r.URL.Path),
		}
		if err := errorResp.VisitListAccountsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Build input from request
	input := &handlers.ListAccountsInput{}
	input.SessionID = sessionID

	// Optional query parameter "accountsFilter"
	if err := runtime.BindQueryParameter("deepObject", true, false, "accountsFilter", r.URL.Query(), &input.AccountsFilter); err != nil {
		errorResp := ListAccounts400Response{
			ProblemDetails: server.NewBadRequestResponse(fmt.Sprintf("Invalid format for parameter accountsFilter: %s", err), r.URL.Path),
		}
		if err := errorResp.VisitListAccountsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Optional query parameter "accountsSort"
	if err := runtime.BindQueryParameter("deepObject", true, false, "accountsSort", r.URL.Query(), &input.AccountsSort); err != nil {
		errorResp := ListAccounts400Response{
			ProblemDetails: server.NewBadRequestResponse(fmt.Sprintf("Invalid format for parameter accountsSort: %s", err), r.URL.Path),
		}
		if err := errorResp.VisitListAccountsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Optional query parameter "page"
	if err := runtime.BindQueryParameter("deepObject", true, false, "page", r.URL.Query(), &input.Page); err != nil {
		errorResp := ListAccounts400Response{
			ProblemDetails: server.NewBadRequestResponse(fmt.Sprintf("Invalid format for parameter page: %s", err), r.URL.Path),
		}
		if err := errorResp.VisitListAccountsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Execute
	result, err := h.listAccounts.Execute(ctx, input)
	if err != nil {
		slog.Error("handler error", "operation", "ListAccounts", "error", err)
		errorResp := ListAccounts500Response{
			ProblemDetails: server.NewInternalServerErrorResponse(err.Error(), r.URL.Path),
		}
		if err := errorResp.VisitListAccountsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Map output to response
	response := ListAccounts200Response{}
	response.Data = result.Data
	response.Meta = result.Meta

	if err := response.VisitListAccountsResponse(w); err != nil {
		fmt.Fprintf(w, "error writing response: %v", err)
	}
}
