// Code generated by archesai. DO NOT EDIT.

package handlers

import (
	"context"

	"github.com/google/uuid"

	"github.com/archesai/archesai/pkg/pipelines/models"
)

// ============================================================================
// GetPipelineExecutionPlan Handler
// ============================================================================

// GetPipelineExecutionPlanInput represents the input for the GetPipelineExecutionPlan operation.
type GetPipelineExecutionPlanInput struct {
	ID uuid.UUID
}

// GetPipelineExecutionPlanOutput represents the output for the GetPipelineExecutionPlan operation.
type GetPipelineExecutionPlanOutput struct {
	Data models.PipelineExecutionPlan `json:"data"`
}

// GetPipelineExecutionPlan defines the interface for the GetPipelineExecutionPlan operation.
type GetPipelineExecutionPlan interface {
	Execute(ctx context.Context, input *GetPipelineExecutionPlanInput) (*GetPipelineExecutionPlanOutput, error)
}
