// Code generated by codegen repository. DO NOT EDIT.
package members

import (
	"context"

	"github.com/google/uuid"
)

// Repository handles member persistence
type Repository interface {
	// Basic CRUD operations (always included)
	Create(ctx context.Context, entity *Member) (*Member, error)
	Get(ctx context.Context, id uuid.UUID) (*Member, error)
	Update(ctx context.Context, id uuid.UUID, entity *Member) (*Member, error)
	Delete(ctx context.Context, id uuid.UUID) error
	List(ctx context.Context, params ListMembersParams) ([]*Member, int64, error)

	// Additional operations
	ListByOrganization(ctx context.Context, organizationID uuid.UUID) ([]*Member, error)
	ListByUser(ctx context.Context, userID uuid.UUID) ([]*Member, error)
	GetByUserAndOrganization(ctx context.Context, userID uuid.UUID, organizationID uuid.UUID) (*Member, error)
}
