// Code generated by archesai. DO NOT EDIT.

package organization

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/archesai/archesai/internal/core/events"
	"github.com/archesai/archesai/internal/core/repositories"
)

// DeleteOrganizationCommand represents the command to delete a organization.
type DeleteOrganizationCommand struct {
	SessionID uuid.UUID
	ID        uuid.UUID
}

// NewDeleteOrganizationCommand creates a new DeleteOrganization command.
func NewDeleteOrganizationCommand(
	SessionID uuid.UUID,
	ID uuid.UUID,
) *DeleteOrganizationCommand {
	return &DeleteOrganizationCommand{
		SessionID: SessionID,
		ID:        ID,
	}
}

// DeleteOrganizationCommandHandler handles the delete organization command.
type DeleteOrganizationCommandHandler struct {
	repo      repositories.OrganizationRepository
	publisher events.Publisher
}

// NewDeleteOrganizationCommandHandler creates a new delete organization command handler.
func NewDeleteOrganizationCommandHandler(
	repo repositories.OrganizationRepository,
	publisher events.Publisher,
) *DeleteOrganizationCommandHandler {
	return &DeleteOrganizationCommandHandler{
		repo:      repo,
		publisher: publisher,
	}
}

// Handle executes the delete organization command.
func (h *DeleteOrganizationCommandHandler) Handle(ctx context.Context, cmd *DeleteOrganizationCommand) error {
	// Delete from repository
	if err := h.repo.Delete(ctx, cmd.ID); err != nil {
		return fmt.Errorf("failed to delete organization: %w", err)
	}

	// Publish domain event
	event := events.NewOrganizationDeletedEvent(cmd.ID)
	if err := h.publisher.Publish(ctx, event); err != nil {
		// Log error but don't fail the operation
	}

	return nil
}
