// Code generated by archesai/codegen. DO NOT EDIT.

package pipelines

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/archesai/archesai/internal/core/entities"
	"github.com/archesai/archesai/internal/core/repositories"
)

// ListPipelinesQuery represents a query to list pipelines.
type ListPipelinesQuery struct {
	SessionID      uuid.UUID
	Limit          int32
	Offset         int32
	OrderBy        string
	OrderDirection string
}

// NewListPipelinesQuery creates a new list pipelines query.
func NewListPipelinesQuery(
	SessionID uuid.UUID,
) *ListPipelinesQuery {
	return &ListPipelinesQuery{
		SessionID: SessionID,
		Limit:     100,
		Offset:    0,
	}
}

// ListPipelinesQueryHandler handles the list pipelines query.
type ListPipelinesQueryHandler struct {
	repo repositories.PipelineRepository
}

// NewListPipelinesQueryHandler creates a new list pipelines query handler.
func NewListPipelinesQueryHandler(repo repositories.PipelineRepository) *ListPipelinesQueryHandler {
	return &ListPipelinesQueryHandler{
		repo: repo,
	}
}

// Handle executes the list pipelines query.
func (h *ListPipelinesQueryHandler) Handle(ctx context.Context, query *ListPipelinesQuery) ([]*entities.Pipeline, int64, error) {
	// TODO: Apply filters based on query parameters
	results, total, err := h.repo.List(ctx, query.Limit, query.Offset)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to list pipelines: %w", err)
	}

	return results, total, nil
}
