// Code generated by archesai. DO NOT EDIT.

package schemas

// UpdateTodoBody represents a UpdateTodoBody
type UpdateTodoBody struct {
	Completed *bool   `json:"completed,omitempty" yaml:"completed,omitempty"`
	Title     *string `json:"title,omitempty" yaml:"title,omitempty"`
}

// NewUpdateTodoBody creates a new immutable UpdateTodoBody value object.
// Value objects are immutable and validated upon creation.
func NewUpdateTodoBody(
	completed *bool,
	title *string,
) (UpdateTodoBody, error) {
	// Validate required fields
	return UpdateTodoBody{
		Completed: completed,
		Title:     title,
	}, nil
}

// ZeroUpdateTodoBody returns the zero value for UpdateTodoBody.
// This is useful for comparisons and as a default value.
func ZeroUpdateTodoBody() UpdateTodoBody {
	return UpdateTodoBody{}
}
