// Code generated by archesai. DO NOT EDIT.

package routes

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"

	"github.com/archesai/archesai/pkg/executor/handlers"
	"github.com/archesai/archesai/pkg/executor/models"
	"github.com/archesai/archesai/pkg/server"
	servermodels "github.com/archesai/archesai/pkg/server/models"
)

// ============================================================================
// ListExecutors - GET /executors
// ============================================================================

// ListExecutorsHandler is the HTTP handler for ListExecutors.
type ListExecutorsHandler struct {
	listExecutors handlers.ListExecutors
}

// NewListExecutorsHandler creates a new HTTP handler.
func NewListExecutorsHandler(listExecutors handlers.ListExecutors) *ListExecutorsHandler {
	return &ListExecutorsHandler{listExecutors: listExecutors}
}

// RegisterListExecutorsRoute registers the HTTP route for ListExecutors.
func RegisterListExecutorsRoute(mux *http.ServeMux, handler *ListExecutorsHandler) {
	mux.HandleFunc("GET /executors", handler.ServeHTTP)
}

// Request types

// ListExecutorsParams defines query parameters for ListExecutors
type ListExecutorsParams struct {
	Filter map[string]any   `json:"filter,omitempty"`
	Page   map[string]any   `json:"page,omitempty"`
	Sort   []map[string]any `json:"sort,omitempty"`
}

// Response types

type ListExecutorsResponse interface {
	VisitListExecutorsResponse(w http.ResponseWriter) error
}

type ListExecutors200Response struct {
	Data []models.Executor           `json:"data"`
	Meta servermodels.PaginationMeta `json:"meta"`
}

func (response ListExecutors200Response) VisitListExecutorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	return json.NewEncoder(w).Encode(response)
}

type ListExecutors400Response struct {
	server.ProblemDetails
}

func (response ListExecutors400Response) VisitListExecutorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type ListExecutors401Response struct {
	server.ProblemDetails
}

func (response ListExecutors401Response) VisitListExecutorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type ListExecutors422Response struct {
	server.ProblemDetails
}

func (response ListExecutors422Response) VisitListExecutorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type ListExecutors429Response struct {
	server.ProblemDetails
}

func (response ListExecutors429Response) VisitListExecutorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type ListExecutors500Response struct {
	server.ProblemDetails
}

func (response ListExecutors500Response) VisitListExecutorsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

// ServeHTTP handles the GET /executors endpoint.
func (h *ListExecutorsHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Build input from request
	input := &handlers.ListExecutorsInput{}

	// Query parameters

	// Optional query parameter "filter"
	if err := runtime.BindQueryParameter("deepObject", true, false, "filter", r.URL.Query(), &input.Filter); err != nil {
		errorResp := ListExecutors400Response{
			ProblemDetails: server.NewBadRequestResponse(fmt.Sprintf("Invalid format for parameter filter: %s", err), r.URL.Path),
		}
		if err := errorResp.VisitListExecutorsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Optional query parameter "page"
	if err := runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &input.Page); err != nil {
		errorResp := ListExecutors400Response{
			ProblemDetails: server.NewBadRequestResponse(fmt.Sprintf("Invalid format for parameter page: %s", err), r.URL.Path),
		}
		if err := errorResp.VisitListExecutorsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Optional query parameter "sort"
	if err := runtime.BindQueryParameter("form", true, false, "sort", r.URL.Query(), &input.Sort); err != nil {
		errorResp := ListExecutors400Response{
			ProblemDetails: server.NewBadRequestResponse(fmt.Sprintf("Invalid format for parameter sort: %s", err), r.URL.Path),
		}
		if err := errorResp.VisitListExecutorsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Execute
	result, err := h.listExecutors.Execute(ctx, input)
	if err != nil {
		errorResp := ListExecutors500Response{
			ProblemDetails: server.NewInternalServerErrorResponse(err.Error(), r.URL.Path),
		}
		if err := errorResp.VisitListExecutorsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Map output to response
	response := ListExecutors200Response{}
	response.Data = result.Data
	response.Meta = result.Meta

	if err := response.VisitListExecutorsResponse(w); err != nil {
		fmt.Fprintf(w, "error writing response: %v", err)
	}
}
