// Code generated by archesai. DO NOT EDIT.

package routes

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"

	"github.com/archesai/archesai/pkg/server"
	"github.com/archesai/archesai/pkg/storage/handlers"
	"github.com/archesai/archesai/pkg/storage/models"
)

// ============================================================================
// UpdateArtifact - PATCH /artifacts/{id}
// ============================================================================

// UpdateArtifactHandler is the HTTP handler for UpdateArtifact.
type UpdateArtifactHandler struct {
	updateArtifact handlers.UpdateArtifact
}

// NewUpdateArtifactHandler creates a new HTTP handler.
func NewUpdateArtifactHandler(updateArtifact handlers.UpdateArtifact) *UpdateArtifactHandler {
	return &UpdateArtifactHandler{updateArtifact: updateArtifact}
}

// RegisterUpdateArtifactRoute registers the HTTP route for UpdateArtifact.
func RegisterUpdateArtifactRoute(mux *http.ServeMux, handler *UpdateArtifactHandler) {
	mux.HandleFunc("PATCH /artifacts/{id}", handler.ServeHTTP)
}

// Request types

// UpdateArtifactRequestBody defines the request body for UpdateArtifact
type UpdateArtifactRequestBody struct {
	Name *string `json:"name,omitempty"`
	Text *string `json:"text,omitempty"`
	URL  *string `json:"url,omitempty"`
}

// Response types

type UpdateArtifactResponse interface {
	VisitUpdateArtifactResponse(w http.ResponseWriter) error
}

type UpdateArtifact200Response struct {
	Data models.Artifact `json:"data"`
}

func (response UpdateArtifact200Response) VisitUpdateArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	return json.NewEncoder(w).Encode(response)
}

type UpdateArtifact400Response struct {
	server.ProblemDetails
}

func (response UpdateArtifact400Response) VisitUpdateArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type UpdateArtifact401Response struct {
	server.ProblemDetails
}

func (response UpdateArtifact401Response) VisitUpdateArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type UpdateArtifact404Response struct {
	server.ProblemDetails
}

func (response UpdateArtifact404Response) VisitUpdateArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type UpdateArtifact422Response struct {
	server.ProblemDetails
}

func (response UpdateArtifact422Response) VisitUpdateArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type UpdateArtifact429Response struct {
	server.ProblemDetails
}

func (response UpdateArtifact429Response) VisitUpdateArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type UpdateArtifact500Response struct {
	server.ProblemDetails
}

func (response UpdateArtifact500Response) VisitUpdateArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

// ServeHTTP handles the PATCH /artifacts/{id} endpoint.
func (h *UpdateArtifactHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Build input from request
	input := &handlers.UpdateArtifactInput{}

	// Path parameter "id"
	var id uuid.UUID
	if err := runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true}); err != nil {
		errorResp := UpdateArtifact400Response{
			ProblemDetails: server.NewBadRequestResponse(fmt.Sprintf("Invalid format for parameter id: %s", err), r.URL.Path),
		}
		if err := errorResp.VisitUpdateArtifactResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}
	input.ID = id

	// Request body
	body := &UpdateArtifactRequestBody{}
	if err := json.NewDecoder(r.Body).Decode(body); err != nil {
		errorResp := UpdateArtifact400Response{
			ProblemDetails: server.NewBadRequestResponse(err.Error(), r.URL.Path),
		}
		if err := errorResp.VisitUpdateArtifactResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}
	input.Name = body.Name
	input.Text = body.Text
	input.URL = body.URL

	// Execute
	result, err := h.updateArtifact.Execute(ctx, input)
	if err != nil {
		errorResp := UpdateArtifact500Response{
			ProblemDetails: server.NewInternalServerErrorResponse(err.Error(), r.URL.Path),
		}
		if err := errorResp.VisitUpdateArtifactResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Map output to response
	response := UpdateArtifact200Response{}
	response.Data = result.Data

	if err := response.VisitUpdateArtifactResponse(w); err != nil {
		fmt.Fprintf(w, "error writing response: %v", err)
	}
}
