// Code generated by archesai-codegen. DO NOT EDIT.

package valueobjects

import (
	"fmt"
	"strings"
)

// KubernetesConfig represents Kubernetes-specific deployment configuration
type KubernetesConfig struct {
	Infrastructure *InfrastructureConfig `json:"infrastructure,omitempty" yaml:"infrastructure,omitempty"`
	Ingress        *IngressConfig        `json:"ingress,omitempty" yaml:"ingress,omitempty"`
	Monitoring     *MonitoringConfig     `json:"monitoring,omitempty" yaml:"monitoring,omitempty"`
}

// NewKubernetesConfig creates a new immutable KubernetesConfig value object.
// Value objects are immutable and validated upon creation.
func NewKubernetesConfig(
	infrastructure *InfrastructureConfig,
	ingress *IngressConfig,
	monitoring *MonitoringConfig,
) (KubernetesConfig, error) {
	// Validate required fields
	return KubernetesConfig{
		Infrastructure: infrastructure,
		Ingress:        ingress,
		Monitoring:     monitoring,
	}, nil
}

// ZeroKubernetesConfig returns the zero value for KubernetesConfig.
// This is useful for comparisons and as a default value.
func ZeroKubernetesConfig() KubernetesConfig {
	return KubernetesConfig{}
}

// GetInfrastructure returns the Infrastructure value.
// Value objects are immutable, so this returns a copy of the value.
func (v KubernetesConfig) GetInfrastructure() *InfrastructureConfig {
	return v.Infrastructure
}

// GetIngress returns the Ingress value.
// Value objects are immutable, so this returns a copy of the value.
func (v KubernetesConfig) GetIngress() *IngressConfig {
	return v.Ingress
}

// GetMonitoring returns the Monitoring value.
// Value objects are immutable, so this returns a copy of the value.
func (v KubernetesConfig) GetMonitoring() *MonitoringConfig {
	return v.Monitoring
}

// Validate validates the KubernetesConfig value object.
// Returns an error if any field fails validation.
func (v KubernetesConfig) Validate() error {
	return nil
}

// IsZero returns true if this is the zero value.
func (v KubernetesConfig) IsZero() bool {
	zero := ZeroKubernetesConfig()
	// Compare using string representation as a simple equality check
	return v.String() == zero.String()
}

// String returns a string representation of KubernetesConfig
func (v KubernetesConfig) String() string {
	var fields []string
	fields = append(fields, fmt.Sprintf("Infrastructure: %v", v.Infrastructure))
	fields = append(fields, fmt.Sprintf("Ingress: %v", v.Ingress))
	fields = append(fields, fmt.Sprintf("Monitoring: %v", v.Monitoring))
	return fmt.Sprintf("KubernetesConfig{%s}", strings.Join(fields, ", "))
}
