// Code generated by archesai/codegen. DO NOT EDIT.

package labels

import (
	"context"

	"github.com/archesai/archesai/internal/core/entities"
	"github.com/archesai/archesai/internal/core/errors"
	"github.com/archesai/archesai/internal/core/repositories"
	"github.com/archesai/archesai/internal/core/valueobjects"
)

// GetLabelQuery represents a query to get a label.
type GetLabelQuery struct {
	ID valueobjects.LabelID
}

// NewGetLabelQuery creates a new get label query.
func NewGetLabelQuery(id valueobjects.LabelID) *GetLabelQuery {
	return &GetLabelQuery{
		ID: id,
	}
}

// GetLabelQueryHandler handles the get label query.
type GetLabelQueryHandler struct {
	repo repositories.LabelRepository
}

// NewGetLabelQueryHandler creates a new get label query handler.
func NewGetLabelQueryHandler(repo repositories.LabelRepository) *GetLabelQueryHandler {
	return &GetLabelQueryHandler{
		repo: repo,
	}
}

// Handle executes the get label query.
func (h *GetLabelQueryHandler) Handle(ctx context.Context, query *GetLabelQuery) (*entities.Label, error) {
	result, err := h.repo.Get(ctx, query.ID)
	if err != nil {
		return nil, errors.Wrap(err, "failed to get label")
	}
	return result, nil
}
