// Code generated by archesai/codegen. DO NOT EDIT.

package users

import (
	"github.com/google/uuid"
)

// GetCurrentUserQuery represents a query to getcurrentuser user.
type GetCurrentUserQuery struct {
	SessionID uuid.UUID
}

// NewGetCurrentUserQuery creates a new getcurrentuser user query.
func NewGetCurrentUserQuery(
	SessionID uuid.UUID,
) *GetCurrentUserQuery {
	return &GetCurrentUserQuery{
		SessionID: SessionID,
	}
}
