// Code generated by archesai/codegen. DO NOT EDIT.

package users

import (
	"context"

	"github.com/archesai/archesai/internal/core/entities"
	"github.com/archesai/archesai/internal/core/errors"
	"github.com/archesai/archesai/internal/core/repositories"
)

// ListUsersQuery represents a query to list users.
type ListUsersQuery struct {
	Limit          int
	Offset         int
	OrderBy        string
	OrderDirection string
}

// NewListUsersQuery creates a new list users query.
func NewListUsersQuery() *ListUsersQuery {
	return &ListUsersQuery{
		Limit:  100,
		Offset: 0,
	}
}

// ListUsersQueryHandler handles the list users query.
type ListUsersQueryHandler struct {
	repo repositories.UserRepository
}

// NewListUsersQueryHandler creates a new list users query handler.
func NewListUsersQueryHandler(repo repositories.UserRepository) *ListUsersQueryHandler {
	return &ListUsersQueryHandler{
		repo: repo,
	}
}

// Handle executes the list users query.
func (h *ListUsersQueryHandler) Handle(ctx context.Context, query *ListUsersQuery) ([]*entities.User, int64, error) {
	// Apply filters
	filters := make(map[string]interface{})
	if query.OrganizationID != "" {
		filters["organization_id"] = query.OrganizationID
	}
	if query.Filter != nil {
		// TODO: Apply advanced filters
	}

	// Execute query with pagination
	results, err := h.repo.List(ctx, filters, query.Limit, query.Offset)
	if err != nil {
		return nil, 0, errors.Wrap(err, "failed to list users")
	}

	// Get total count
	total, err := h.repo.Count(ctx, filters)
	if err != nil {
		return nil, 0, errors.Wrap(err, "failed to count users")
	}

	return results, total, nil
}
