// Code generated by archesai. DO NOT EDIT.

package bootstrap

import (
	"github.com/archesai/archesai/pkg/events"
	"github.com/archesai/archesai/pkg/storage/application"
	"github.com/archesai/archesai/pkg/storage/repositories"
)

// ApplicationHandlers holds all application-layer handlers for this package.
type ApplicationHandlers struct {
	CreateArtifact application.CreateArtifact
	CreateLabel    application.CreateLabel
	DeleteArtifact application.DeleteArtifact
	DeleteLabel    application.DeleteLabel
	GetArtifact    application.GetArtifact
	GetLabel       application.GetLabel
	ListArtifacts  application.ListArtifacts
	ListLabels     application.ListLabels
	UpdateArtifact application.UpdateArtifact
	UpdateLabel    application.UpdateLabel
}

// NewApplicationHandlers creates all application handlers with proper dependency injection.
func NewApplicationHandlers(
	artifactRepo repositories.ArtifactRepository,
	labelRepo repositories.LabelRepository,
	publisher events.Publisher,
) *ApplicationHandlers {
	return &ApplicationHandlers{
		CreateArtifact: application.NewCreateArtifact(artifactRepo, publisher),
		CreateLabel:    application.NewCreateLabel(labelRepo, publisher),
		DeleteArtifact: application.NewDeleteArtifact(artifactRepo, publisher),
		DeleteLabel:    application.NewDeleteLabel(labelRepo, publisher),
		GetArtifact:    application.NewGetArtifact(artifactRepo),
		GetLabel:       application.NewGetLabel(labelRepo),
		ListArtifacts:  application.NewListArtifacts(artifactRepo),
		ListLabels:     application.NewListLabels(labelRepo),
		UpdateArtifact: application.NewUpdateArtifact(artifactRepo, publisher),
		UpdateLabel:    application.NewUpdateLabel(labelRepo, publisher),
	}
}
