// Code generated by archesai. DO NOT EDIT.

package http

import (
	"errors"
	"log/slog"
	"net/http"

	"github.com/archesai/archesai/pkg/httputil"
	"github.com/archesai/archesai/pkg/validation"
	"github.com/archesai/examples/basic/operations"
	"github.com/archesai/examples/basic/schemas"
)

// ============================================================================
// CreateTodo - POST /todos
// ============================================================================

// CreateTodoHandler is the HTTP handler for CreateTodo.
type CreateTodoHandler struct {
	createTodo operations.CreateTodo
}

// NewCreateTodoHandler creates a new HTTP handler.
func NewCreateTodoHandler(createTodo operations.CreateTodo) *CreateTodoHandler {
	return &CreateTodoHandler{createTodo: createTodo}
}

// RegisterCreateTodoRoute registers the HTTP route for CreateTodo.
func RegisterCreateTodoRoute(mux *http.ServeMux, handler *CreateTodoHandler) {
	mux.HandleFunc("POST /todos", handler.ServeHTTP)
}

// CreateTodoRequestBody defines the request body for CreateTodo
type CreateTodoRequestBody struct {
	Completed *bool  `json:"completed,omitempty"`
	Title     string `json:"title"`
}

// Validate implements the validation.Validator interface.
func (b *CreateTodoRequestBody) Validate() validation.Errors {
	var errs validation.Errors
	validation.RequiredString(b.Title, "title", &errs)
	validation.MinLengthString(b.Title, 1, "title", &errs)
	validation.MaxLengthString(b.Title, 255, "title", &errs)
	return errs
}

// Response Types

// CreateTodo201Response is the 201 success response.
type CreateTodo201Response struct {
	Data schemas.Todo `json:"data"`
}

// StatusCode returns the HTTP status code.
func (CreateTodo201Response) StatusCode() int { return 201 }

// CreateTodo400Response is the 400 error response.
type CreateTodo400Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (CreateTodo400Response) StatusCode() int { return 400 }

// CreateTodo401Response is the 401 error response.
type CreateTodo401Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (CreateTodo401Response) StatusCode() int { return 401 }

// CreateTodo422Response is the 422 error response.
type CreateTodo422Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (CreateTodo422Response) StatusCode() int { return 422 }

// CreateTodo429Response is the 429 error response.
type CreateTodo429Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (CreateTodo429Response) StatusCode() int { return 429 }

// CreateTodo500Response is the 500 error response.
type CreateTodo500Response struct {
	httputil.ProblemDetails
}

// StatusCode returns the HTTP status code.
func (CreateTodo500Response) StatusCode() int { return 500 }

// ServeHTTP handles the POST /todos endpoint.
func (h *CreateTodoHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Build input from request
	input := &operations.CreateTodoInput{}

	// Request body
	var body CreateTodoRequestBody
	if err := httputil.DecodeAndValidate(r, &body); err != nil {
		var validErrs validation.Errors
		if errors.As(err, &validErrs) {
			_ = httputil.WriteValidationErrors(w, validErrs, r.URL.Path)
			return
		}
		_ = httputil.WriteResponse(w, CreateTodo400Response{
			ProblemDetails: httputil.NewBadRequestResponse(err.Error(), r.URL.Path),
		})
		return
	}
	input.Completed = body.Completed
	input.Title = body.Title

	// Execute handler
	result, err := h.createTodo.Execute(ctx, input)
	if err != nil {
		var httpErr httputil.HTTPError
		if errors.As(err, &httpErr) {
			_ = httputil.WriteHTTPError(w, httpErr, r.URL.Path)
			return
		}
		slog.Error("handler error", "operation", "CreateTodo", "error", err)
		_ = httputil.WriteResponse(w, CreateTodo500Response{
			ProblemDetails: httputil.NewInternalServerErrorResponse(err.Error(), r.URL.Path),
		})
		return
	}

	// Build and send response
	_ = httputil.WriteResponse(w, CreateTodo201Response{
		Data: result.Data,
	})
}
