export default () => ({
  // GLOBAL CONFIG
  NODE_ENV: process.env.NODE_ENV,
  SERVER_HOST: process.env.SERVER_HOST,
  FRONTEND_HOST: process.env.FRONTEND_HOST,
  PORT: parseInt(process.env.PORT, 10),
  ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS,

  // DATABASE CONFIG
  DATABASE_URL: process.env.DATABASE_URL,

  // EMAIL CONFIG
  FEATURE_EMAIL: process.env.FEATURE_EMAIL,
  EMAIL_USER: process.env.EMAIL_USER,
  EMAIL_PASSWORD: process.env.EMAIL_PASSWORD,
  EMAIL_SERVICE: process.env.EMAIL_SERVICE,

  // EMBEDDING CONFIG
  EMBEDDING_TYPE: process.env.EMBEDDING_TYPE,

  // JWT CONFIG
  JWT_API_TOKEN_EXPIRATION_TIME: process.env.JWT_API_TOKEN_EXPIRATION_TIME,
  JWT_API_TOKEN_SECRET: process.env.JWT_API_TOKEN_SECRET,

  // BILLING CONFIG
  FEATURE_BILLING: process.env.FEATURE_BILLING,
  STRIPE_PRIVATE_API_KEY: process.env.STRIPE_PRIVATE_API_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,

  // LLM CONFIG
  LLM_TYPE: process.env.LLM_TYPE,
  LLM_ENDPOINT: process.env.LLM_ENDPOINT,
  LLM_API_KEY: process.env.LLM_API_KEY,

  // LOADER CONFIG
  LOADER_ENDPOINT: process.env.LOADER_ENDPOINT,

  // STORAGE CONFIG
  STORAGE_TYPE: process.env.STORAGE_TYPE,

  // REDIS CONFIG
  REDIS_AUTH: process.env.REDIS_AUTH,
  REDIS_CA_CERT_PATH: process.env.REDIS_CA_CERT_PATH,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: parseInt(process.env.REDIS_PORT, 10),

  // SESSION CONFIG
  SESSION_SECRET: process.env.SESSION_SECRET,

  // LOGGING CONFIG
  LOGGING_LEVEL: process.env.LOGGING_LEVEL,
  LOKI_HOST: process.env.LOKI_HOST
})
