// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api-tokens.sql

package postgresql

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO
  api_token (
    id,
    user_id,
    organization_id,
    name,
    key_hash,
    prefix,
    scopes,
    rate_limit,
    expires_at
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
  id, created_at, updated_at, expires_at, key_hash, name, prefix, user_id, organization_id, scopes, rate_limit, last_used_at
`

type CreateAPIKeyParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Name           *string
	KeyHash        string
	Prefix         *string
	Scopes         []string
	RateLimit      int32
	ExpiresAt      *time.Time
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (APIToken, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.OrganizationID,
		arg.Name,
		arg.KeyHash,
		arg.Prefix,
		arg.Scopes,
		arg.RateLimit,
		arg.ExpiresAt,
	)
	var i APIToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.KeyHash,
		&i.Name,
		&i.Prefix,
		&i.UserID,
		&i.OrganizationID,
		&i.Scopes,
		&i.RateLimit,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_token
WHERE
  id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, id)
	return err
}

const deleteAPIKeysByUser = `-- name: DeleteAPIKeysByUser :exec
DELETE FROM api_token
WHERE
  user_id = $1
`

func (q *Queries) DeleteAPIKeysByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIKeysByUser, userID)
	return err
}

const deleteExpiredAPIKeys = `-- name: DeleteExpiredAPIKeys :exec
DELETE FROM api_token
WHERE
  expires_at IS NOT NULL
  AND expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredAPIKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAPIKeys)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT
  id, created_at, updated_at, expires_at, key_hash, name, prefix, user_id, organization_id, scopes, rate_limit, last_used_at
FROM
  api_token
WHERE
  id = $1
LIMIT
  1
`

func (q *Queries) GetAPIKey(ctx context.Context, id uuid.UUID) (APIToken, error) {
	row := q.db.QueryRow(ctx, getAPIKey, id)
	var i APIToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.KeyHash,
		&i.Name,
		&i.Prefix,
		&i.UserID,
		&i.OrganizationID,
		&i.Scopes,
		&i.RateLimit,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPIKeyByKeyHash = `-- name: GetAPIKeyByKeyHash :one
SELECT
  id, created_at, updated_at, expires_at, key_hash, name, prefix, user_id, organization_id, scopes, rate_limit, last_used_at
FROM
  api_token
WHERE
  key_hash = $1
LIMIT
  1
`

func (q *Queries) GetAPIKeyByKeyHash(ctx context.Context, keyHash string) (APIToken, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByKeyHash, keyHash)
	var i APIToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.KeyHash,
		&i.Name,
		&i.Prefix,
		&i.UserID,
		&i.OrganizationID,
		&i.Scopes,
		&i.RateLimit,
		&i.LastUsedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT
  id, created_at, updated_at, expires_at, key_hash, name, prefix, user_id, organization_id, scopes, rate_limit, last_used_at
FROM
  api_token
ORDER BY
  created_at DESC
LIMIT
  $1
OFFSET
  $2
`

type ListAPIKeysParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]APIToken, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIToken
	for rows.Next() {
		var i APIToken
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.KeyHash,
			&i.Name,
			&i.Prefix,
			&i.UserID,
			&i.OrganizationID,
			&i.Scopes,
			&i.RateLimit,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByOrganization = `-- name: ListAPIKeysByOrganization :many
SELECT
  id, created_at, updated_at, expires_at, key_hash, name, prefix, user_id, organization_id, scopes, rate_limit, last_used_at
FROM
  api_token
WHERE
  organization_id = $1
ORDER BY
  created_at DESC
LIMIT
  $2
OFFSET
  $3
`

type ListAPIKeysByOrganizationParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

func (q *Queries) ListAPIKeysByOrganization(ctx context.Context, arg ListAPIKeysByOrganizationParams) ([]APIToken, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIToken
	for rows.Next() {
		var i APIToken
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.KeyHash,
			&i.Name,
			&i.Prefix,
			&i.UserID,
			&i.OrganizationID,
			&i.Scopes,
			&i.RateLimit,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT
  id, created_at, updated_at, expires_at, key_hash, name, prefix, user_id, organization_id, scopes, rate_limit, last_used_at
FROM
  api_token
WHERE
  user_id = $1
ORDER BY
  created_at DESC
LIMIT
  $2
OFFSET
  $3
`

type ListAPIKeysByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListAPIKeysByUser(ctx context.Context, arg ListAPIKeysByUserParams) ([]APIToken, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIToken
	for rows.Next() {
		var i APIToken
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.KeyHash,
			&i.Name,
			&i.Prefix,
			&i.UserID,
			&i.OrganizationID,
			&i.Scopes,
			&i.RateLimit,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKey = `-- name: UpdateAPIKey :one
UPDATE api_token
SET
  name = COALESCE($1, name),
  scopes = COALESCE($2, scopes),
  rate_limit = COALESCE($3, rate_limit),
  expires_at = COALESCE($4, expires_at),
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = $5
RETURNING
  id, created_at, updated_at, expires_at, key_hash, name, prefix, user_id, organization_id, scopes, rate_limit, last_used_at
`

type UpdateAPIKeyParams struct {
	Name      *string
	Scopes    []string
	RateLimit *int32
	ExpiresAt *time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (APIToken, error) {
	row := q.db.QueryRow(ctx, updateAPIKey,
		arg.Name,
		arg.Scopes,
		arg.RateLimit,
		arg.ExpiresAt,
		arg.ID,
	)
	var i APIToken
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.KeyHash,
		&i.Name,
		&i.Prefix,
		&i.UserID,
		&i.OrganizationID,
		&i.Scopes,
		&i.RateLimit,
		&i.LastUsedAt,
	)
	return i, err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_token
SET
  last_used_at = CURRENT_TIMESTAMP
WHERE
  id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
