// Code generated by archesai. DO NOT EDIT.

package handlers

import (
	"context"
	"fmt"

	"github.com/google/uuid"

	"github.com/archesai/archesai/pkg/storage/models"
	"github.com/archesai/archesai/pkg/storage/repositories"
)

// ============================================================================
// GetLabel Handler
// ============================================================================

// GetLabelInput represents the input for the GetLabel operation.
type GetLabelInput struct {
	ID uuid.UUID
}

// GetLabelOutput represents the output for the GetLabel operation.
type GetLabelOutput struct {
	Data models.Label `json:"data"`
}

// GetLabel defines the interface for the GetLabel operation.
type GetLabel interface {
	Execute(ctx context.Context, input *GetLabelInput) (*GetLabelOutput, error)
}

// GetLabelImpl is the default implementation of GetLabel.
type GetLabelImpl struct {
	repo repositories.LabelRepository
}

// NewGetLabel creates a new GetLabel handler.
func NewGetLabel(
	repo repositories.LabelRepository,
) GetLabel {
	return &GetLabelImpl{
		repo: repo,
	}
}

// Execute performs the GetLabel operation.
func (h *GetLabelImpl) Execute(ctx context.Context, input *GetLabelInput) (*GetLabelOutput, error) {
	// Get from repository
	result, err := h.repo.Get(ctx, input.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get label: %w", err)
	}

	// Map to output
	output := &GetLabelOutput{
		// TODO: Map result fields to output
	}
	_ = result

	return output, nil
}
