// Code generated by archesai/codegen. DO NOT EDIT.

package auth

import (
	"github.com/google/uuid"
)

// ConfirmEmailVerificationCommand represents the command to confirmemailverification a auth.
type ConfirmEmailVerificationCommand struct {
	SessionID uuid.UUID
	Token     string
}

// NewConfirmEmailVerificationCommand creates a new confirmemailverification auth command.
func NewConfirmEmailVerificationCommand(
	SessionID uuid.UUID,
	Token string,
) *ConfirmEmailVerificationCommand {
	return &ConfirmEmailVerificationCommand{
		SessionID: SessionID,
		Token:     Token,
	}
}
