// Code generated by archesai/codegen. DO NOT EDIT.

package auth

import (
	"github.com/google/uuid"
)

// RequestEmailChangeCommand represents the command to requestemailchange a auth.
type RequestEmailChangeCommand struct {
	SessionID uuid.UUID
	NewEmail  string
	UserID    uuid.UUID
}

// NewRequestEmailChangeCommand creates a new requestemailchange auth command.
func NewRequestEmailChangeCommand(
	SessionID uuid.UUID,
	NewEmail string,
	UserID uuid.UUID,
) *RequestEmailChangeCommand {
	return &RequestEmailChangeCommand{
		SessionID: SessionID,
		NewEmail:  NewEmail,
		UserID:    UserID,
	}
}
