// Code generated by archesai/codegen. DO NOT EDIT.

package auth

// RequestMagicLinkAuthCommand represents the command to requestmagiclink a auth.
type RequestMagicLinkAuthCommand struct {
}

// NewRequestMagicLinkAuthCommand creates a new requestmagiclink auth command.
func NewRequestMagicLinkAuthCommand() *RequestMagicLinkAuthCommand {
	return &RequestMagicLinkAuthCommand{}
}
