// Code generated by archesai. DO NOT EDIT.

package controllers

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/google/uuid"

	"github.com/archesai/archesai/pkg/auth/application"
	"github.com/archesai/archesai/pkg/server"
)

// ============================================================================
// Login - POST /auth/login
// ============================================================================

// Handler type

// LoginHandlerHTTP wraps the user handler for HTTP
type LoginHandlerHTTP struct {
	handler application.LoginHandler
}

// NewLoginHandlerHTTP creates a new HTTP handler wrapper
func NewLoginHandlerHTTP(handler application.LoginHandler) *LoginHandlerHTTP {
	return &LoginHandlerHTTP{handler: handler}
}

// RegisterLoginRoute registers the HTTP route for Login
func RegisterLoginRoute(mux *http.ServeMux, handler *LoginHandlerHTTP) {
	mux.HandleFunc("POST /auth/login", handler.ServeHTTP)
}

// Request types

// LoginRequestBody defines the request body for Login
type LoginRequestBody struct {
	Email      string `json:"email"`
	Password   string `json:"password"`
	RememberMe *bool  `json:"rememberMe,omitempty"`
}

// Response types

type LoginResponse interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login201Response struct {
	ID             uuid.UUID  `json:"id"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      time.Time  `json:"updatedAt"`
	AuthMethod     *string    `json:"authMethod"`
	AuthProvider   *string    `json:"authProvider"`
	ExpiresAt      time.Time  `json:"expiresAt"`
	IPAddress      *string    `json:"ipAddress"`
	OrganizationID *uuid.UUID `json:"organizationID"`
	Token          string     `json:"token"`
	UserAgent      *string    `json:"userAgent"`
	UserID         uuid.UUID  `json:"userID"`
}

func (response Login201Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	return json.NewEncoder(w).Encode(response)
}

type Login400Response struct {
	server.ProblemDetails
}

func (response Login400Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type Login401Response struct {
	server.ProblemDetails
}

func (response Login401Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type Login422Response struct {
	server.ProblemDetails
}

func (response Login422Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type Login429Response struct {
	server.ProblemDetails
}

func (response Login429Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type Login500Response struct {
	server.ProblemDetails
}

func (response Login500Response) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

// ServeHTTP handles the POST /auth/login endpoint.
func (h *LoginHandlerHTTP) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Build input from request
	input := &application.LoginInput{}

	// Request body
	body := &LoginRequestBody{}
	if err := json.NewDecoder(r.Body).Decode(body); err != nil {
		errorResp := Login400Response{
			ProblemDetails: server.NewBadRequestResponse(err.Error(), r.URL.Path),
		}
		if err := errorResp.VisitLoginResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}
	input.Email = body.Email
	input.Password = body.Password
	input.RememberMe = body.RememberMe

	// Execute handler
	result, err := h.handler.Execute(ctx, input)
	if err != nil {
		errorResp := Login500Response{
			ProblemDetails: server.NewInternalServerErrorResponse(err.Error(), r.URL.Path),
		}
		if err := errorResp.VisitLoginResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Map output to response
	response := Login201Response{}
	response.ID = result.ID
	response.CreatedAt = result.CreatedAt
	response.UpdatedAt = result.UpdatedAt
	response.AuthMethod = result.AuthMethod
	response.AuthProvider = result.AuthProvider
	response.ExpiresAt = result.ExpiresAt
	response.IPAddress = result.IPAddress
	response.OrganizationID = result.OrganizationID
	response.Token = result.Token
	response.UserAgent = result.UserAgent
	response.UserID = result.UserID

	if err := response.VisitLoginResponse(w); err != nil {
		fmt.Fprintf(w, "error writing response: %v", err)
	}
}
