// Code generated by archesai. DO NOT EDIT.

package controllers

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"

	"github.com/archesai/archesai/pkg/pipelines/application"
	"github.com/archesai/archesai/pkg/pipelines/models"
	"github.com/archesai/archesai/pkg/server"
)

// ============================================================================
// GetPipelineSteps - GET /pipelines/{id}/steps
// ============================================================================

// Handler type

// GetPipelineStepsHandlerHTTP wraps the user handler for HTTP
type GetPipelineStepsHandlerHTTP struct {
	handler application.GetPipelineStepsHandler
}

// NewGetPipelineStepsHandlerHTTP creates a new HTTP handler wrapper
func NewGetPipelineStepsHandlerHTTP(handler application.GetPipelineStepsHandler) *GetPipelineStepsHandlerHTTP {
	return &GetPipelineStepsHandlerHTTP{handler: handler}
}

// RegisterGetPipelineStepsRoute registers the HTTP route for GetPipelineSteps
func RegisterGetPipelineStepsRoute(mux *http.ServeMux, handler *GetPipelineStepsHandlerHTTP) {
	mux.HandleFunc("GET /pipelines/{id}/steps", handler.ServeHTTP)
}

// Request types

// Response types

type GetPipelineStepsResponse interface {
	VisitGetPipelineStepsResponse(w http.ResponseWriter) error
}

type GetPipelineSteps200Response struct {
	Data []models.PipelineStep `json:"data"`
}

func (response GetPipelineSteps200Response) VisitGetPipelineStepsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	return json.NewEncoder(w).Encode(response)
}

type GetPipelineSteps400Response struct {
	server.ProblemDetails
}

func (response GetPipelineSteps400Response) VisitGetPipelineStepsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type GetPipelineSteps401Response struct {
	server.ProblemDetails
}

func (response GetPipelineSteps401Response) VisitGetPipelineStepsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type GetPipelineSteps404Response struct {
	server.ProblemDetails
}

func (response GetPipelineSteps404Response) VisitGetPipelineStepsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type GetPipelineSteps422Response struct {
	server.ProblemDetails
}

func (response GetPipelineSteps422Response) VisitGetPipelineStepsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type GetPipelineSteps429Response struct {
	server.ProblemDetails
}

func (response GetPipelineSteps429Response) VisitGetPipelineStepsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type GetPipelineSteps500Response struct {
	server.ProblemDetails
}

func (response GetPipelineSteps500Response) VisitGetPipelineStepsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

// ServeHTTP handles the GET /pipelines/{id}/steps endpoint.
func (h *GetPipelineStepsHandlerHTTP) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Build input from request
	input := &application.GetPipelineStepsInput{}

	// Path parameter "id"
	var id uuid.UUID
	if err := runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true}); err != nil {
		errorResp := GetPipelineSteps400Response{
			ProblemDetails: server.NewBadRequestResponse(fmt.Sprintf("Invalid format for parameter id: %s", err), r.URL.Path),
		}
		if err := errorResp.VisitGetPipelineStepsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}
	input.ID = id

	// Execute handler
	result, err := h.handler.Execute(ctx, input)
	if err != nil {
		errorResp := GetPipelineSteps500Response{
			ProblemDetails: server.NewInternalServerErrorResponse(err.Error(), r.URL.Path),
		}
		if err := errorResp.VisitGetPipelineStepsResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	// Map output to response
	response := GetPipelineSteps200Response{}
	response.Data = result.Data

	if err := response.VisitGetPipelineStepsResponse(w); err != nil {
		fmt.Fprintf(w, "error writing response: %v", err)
	}
}
