// Code generated by archesai. DO NOT EDIT.

package controllers

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"

	"github.com/archesai/archesai/pkg/server"
	"github.com/archesai/archesai/pkg/storage/application"
)

// ============================================================================
// DeleteLabel - DELETE /labels/{id}
// ============================================================================

// Handler type

// DeleteLabelHandlerHTTP wraps the user handler for HTTP
type DeleteLabelHandlerHTTP struct {
	handler application.DeleteLabelHandler
}

// NewDeleteLabelHandlerHTTP creates a new HTTP handler wrapper
func NewDeleteLabelHandlerHTTP(handler application.DeleteLabelHandler) *DeleteLabelHandlerHTTP {
	return &DeleteLabelHandlerHTTP{handler: handler}
}

// RegisterDeleteLabelRoute registers the HTTP route for DeleteLabel
func RegisterDeleteLabelRoute(mux *http.ServeMux, handler *DeleteLabelHandlerHTTP) {
	mux.HandleFunc("DELETE /labels/{id}", handler.ServeHTTP)
}

// Request types

// Response types

type DeleteLabelResponse interface {
	VisitDeleteLabelResponse(w http.ResponseWriter) error
}

type DeleteLabel204Response struct {
}

func (response DeleteLabel204Response) VisitDeleteLabelResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteLabel400Response struct {
	server.ProblemDetails
}

func (response DeleteLabel400Response) VisitDeleteLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type DeleteLabel401Response struct {
	server.ProblemDetails
}

func (response DeleteLabel401Response) VisitDeleteLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type DeleteLabel404Response struct {
	server.ProblemDetails
}

func (response DeleteLabel404Response) VisitDeleteLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type DeleteLabel422Response struct {
	server.ProblemDetails
}

func (response DeleteLabel422Response) VisitDeleteLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type DeleteLabel429Response struct {
	server.ProblemDetails
}

func (response DeleteLabel429Response) VisitDeleteLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

type DeleteLabel500Response struct {
	server.ProblemDetails
}

func (response DeleteLabel500Response) VisitDeleteLabelResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	return json.NewEncoder(w).Encode(response.ProblemDetails)
}

// ServeHTTP handles the DELETE /labels/{id} endpoint.
func (h *DeleteLabelHandlerHTTP) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	// Build input from request
	input := &application.DeleteLabelInput{}

	// Path parameter "id"
	var id uuid.UUID
	if err := runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true}); err != nil {
		errorResp := DeleteLabel400Response{
			ProblemDetails: server.NewBadRequestResponse(fmt.Sprintf("Invalid format for parameter id: %s", err), r.URL.Path),
		}
		if err := errorResp.VisitDeleteLabelResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}
	input.ID = id

	// Execute handler
	if err := h.handler.Execute(ctx, input); err != nil {
		errorResp := DeleteLabel500Response{
			ProblemDetails: server.NewInternalServerErrorResponse(err.Error(), r.URL.Path),
		}
		if err := errorResp.VisitDeleteLabelResponse(w); err != nil {
			fmt.Fprintf(w, "error writing response: %v", err)
		}
		return
	}

	response := DeleteLabel204Response{}
	if err := response.VisitDeleteLabelResponse(w); err != nil {
		fmt.Fprintf(w, "error writing response: %v", err)
	}
}
