// Code generated by codegen repository. DO NOT EDIT.
package repositories

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/archesai/archesai/internal/application/dto"
	"github.com/archesai/archesai/internal/core/entities"
	"github.com/archesai/archesai/internal/core/errors"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"
)

// PostgresInvitationRepository implements InvitationRepository using PostgreSQL.
type PostgresInvitationRepository struct {
	queries *Queries
}

// NewPostgresInvitationRepository creates a new PostgreSQL repository.
func NewPostgresInvitationRepository(db *pgxpool.Pool) *PostgresInvitationRepository {
	return &PostgresInvitationRepository{
		queries: New(db),
	}
}

// Invitation operations

// Create creates a new invitation
func (r *PostgresInvitationRepository) Create(ctx context.Context, entity *entities.Invitation) (*entities.Invitation, error) {
	params := CreateInvitationParams{
		ID: entity.ID,
	}

	result, err := r.queries.CreateInvitation(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("failed to create invitation: %w", err)
	}

	return mapInvitationFromDB(&result), nil
}

// Get retrieves a invitation by ID
func (r *PostgresInvitationRepository) Get(ctx context.Context, id uuid.UUID) (*entities.Invitation, error) {
	result, err := r.queries.GetInvitation(ctx, id)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, errors.ErrInvitationNotFound
		}
		return nil, fmt.Errorf("failed to get invitation: %w", err)
	}

	return mapInvitationFromDB(&result), nil
}

// Update updates an existing invitation
func (r *PostgresInvitationRepository) Update(ctx context.Context, id uuid.UUID, entity *entities.Invitation) (*entities.Invitation, error) {
	params := UpdateInvitationParams{
		ID: id,
	}

	result, err := r.queries.UpdateInvitation(ctx, params)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, errors.ErrInvitationNotFound
		}
		return nil, fmt.Errorf("failed to update invitation: %w", err)
	}

	return mapInvitationFromDB(&result), nil
}

// Delete removes a invitation
func (r *PostgresInvitationRepository) Delete(ctx context.Context, id uuid.UUID) error {
	err := r.queries.DeleteInvitation(ctx, id)
	if err != nil {
		if err == sql.ErrNoRows {
			return errors.ErrInvitationNotFound
		}
		return fmt.Errorf("failed to delete invitation: %w", err)
	}
	return nil
}

// List returns a paginated list of invitations
func (r *PostgresInvitationRepository) List(ctx context.Context, params dto.ListInvitationsParams) ([]*entities.Invitation, int64, error) {
	// Calculate offset from page
	offset := int32(0)
	limit := int32(10) // default

	// Check if params has Page field with Limit and Offset
	if params.Page != nil {
		if params.Page.Offset != nil && *params.Page.Offset >= 0 {
			offset = int32(*params.Page.Offset)
		}
		if params.Page.Limit != nil && *params.Page.Limit > 0 {
			limit = int32(*params.Page.Limit)
		}
	}

	listParams := ListInvitationsParams{
		Limit:  limit,
		Offset: offset,
	}

	results, err := r.queries.ListInvitations(ctx, listParams)
	if err != nil {
		return nil, 0, fmt.Errorf("failed to list invitations: %w", err)
	}

	items := make([]*entities.Invitation, len(results))
	for i, result := range results {
		items[i] = mapInvitationFromDB(&result)
	}

	// For now, return the count as the length of results
	// In production, you'd want a separate count query
	count := int64(len(results))

	return items, count, nil
}

// Additional methods

// ListByOrganization retrieves multiple invitations by organizationID
func (r *PostgresInvitationRepository) ListByOrganization(ctx context.Context, organizationID string) ([]*entities.Invitation, error) {

	// TODO: Implement ListByOrganization - fetch multiple invitations
	return nil, fmt.Errorf("ListByOrganization not yet implemented")

}

// GetByEmail retrieves a single invitation by email and organizationID
func (r *PostgresInvitationRepository) GetByEmail(ctx context.Context, email string, organizationID string) (*entities.Invitation, error) {

	// TODO: Implement GetByEmail - fetch single invitation
	return nil, fmt.Errorf("GetByEmail not yet implemented")

}

// ListByInviter retrieves multiple invitations by inviterID
func (r *PostgresInvitationRepository) ListByInviter(ctx context.Context, inviterID string) ([]*entities.Invitation, error) {

	// TODO: Implement ListByInviter - fetch multiple invitations
	return nil, fmt.Errorf("ListByInviter not yet implemented")

}

func mapInvitationFromDB(db *Invitation) *entities.Invitation {
	if db == nil {
		return nil
	}

	result := &entities.Invitation{
		ID:        db.ID,
		CreatedAt: db.CreatedAt,
		UpdatedAt: db.UpdatedAt,
	}

	return result
}
