// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repositories

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type APIToken struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ExpiresAt      *time.Time
	KeyHash        string
	Name           *string
	Prefix         *string
	UserID         uuid.UUID
	OrganizationID uuid.UUID
	Scopes         []string
	RateLimit      int32
	LastUsedAt     *time.Time
}

type Account struct {
	ID                    uuid.UUID
	CreatedAt             time.Time
	UpdatedAt             time.Time
	AccessToken           *string
	AccessTokenExpiresAt  *time.Time
	AccountID             string
	IDToken               *string
	Password              *string
	ProviderID            string
	RefreshToken          *string
	RefreshTokenExpiresAt *time.Time
	Scope                 *string
	UserID                uuid.UUID
}

type Artifact struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Credits        int32
	Description    *string
	MimeType       string
	Name           *string
	OrganizationID uuid.UUID
	PreviewImage   *string
	ProducerID     *uuid.UUID
	Text           *string
	URL            *string
	Embedding      *pgvector.Vector
}

type Invitation struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	ExpiresAt      time.Time
	InviterID      uuid.UUID
	OrganizationID uuid.UUID
	Role           string
	Status         string
}

type Label struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	OrganizationID uuid.UUID
}

type LabelToArtifact struct {
	LabelID    uuid.UUID
	ArtifactID uuid.UUID
}

type MagicLinkToken struct {
	ID             uuid.UUID
	UserID         *uuid.UUID
	TokenHash      string
	Code           *string
	Identifier     string
	DeliveryMethod *string
	ExpiresAt      pgtype.Timestamp
	UsedAt         pgtype.Timestamp
	IPAddress      *string
	UserAgent      *string
	CreatedAt      pgtype.Timestamp
}

type Member struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OrganizationID uuid.UUID
	Role           string
	UserID         uuid.UUID
}

type Organization struct {
	ID               uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	BillingEmail     *string
	Credits          int32
	Logo             *string
	Name             string
	Plan             string
	StripeCustomerID *string
	Slug             string
}

type Pipeline struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Description    *string
	Name           *string
	OrganizationID uuid.UUID
}

type PipelineStep struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	PipelineID uuid.UUID
	ToolID     uuid.UUID
}

type PipelineStepToDependency struct {
	PipelineStepID uuid.UUID
	PrerequisiteID uuid.UUID
}

type Run struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    *time.Time
	Error          *string
	OrganizationID uuid.UUID
	PipelineID     uuid.UUID
	Progress       float64
	StartedAt      *time.Time
	Status         string
	ToolID         uuid.UUID
}

type RunToArtifact struct {
	RunID      uuid.UUID
	ArtifactID uuid.UUID
}

type Session struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	OrganizationID *uuid.UUID
	ExpiresAt      time.Time
	IPAddress      *string
	Token          string
	UserAgent      *string
	UserID         uuid.UUID
	AuthMethod     *string
	AuthProvider   *string
	Metadata       []byte
}

type Tool struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Description    string
	InputMimeType  string
	Name           string
	OrganizationID uuid.UUID
	OutputMimeType string
}

type User struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Email         string
	EmailVerified bool
	Image         *string
	Name          string
}

type VerificationToken struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ExpiresAt  time.Time
	Identifier string
	Value      string
}
